#!/usr/bin/env python3
"""Load and save cost, measured in emulated time on each target.

Not part of the suite: a bench.  Each row is one openMSX session that either
loads a document at boot (LOADDOC entry -> LOADDOC.CLSFIL) or saves it with
Ctrl+S (FILESAVE entry -> its DSKCLOSE).  Both ends are breakpoints in our own
code, and every save is read back off the disk and compared with the fixture,
so a faster number can never hide a wrong file.

    python3 bench_io.py                 # every row
    python3 bench_io.py s2              # rows whose name contains "s2"
"""

import os
import sys

from cases import Case, crlf, numbered
from context import Context
from gate_s2 import S2_CFG
from harness import MACH_128K, MACH_2MB, MACH_MSX1, MACH_MSX1_1M
from keys import Timeline

HERE = os.path.dirname(os.path.abspath(__file__))
MANUAL = os.path.join(os.path.dirname(HERE), 'CODE', 'SXED_MSX.TXT')

BENCH_CFG = """; generated by bench_io.py
PROFILE=STD
WRAP=DEV
MARKUP=OFF
CLOCK=0
TABWIDTH=4
EOL=AUTO
AUTOALIGN=OFF
"""


def manual():
    with open(MANUAL, 'rb') as fh:
        return fh.read()


def small():
    # Fits every 128 kB ceiling (101 / 131 / 127 lines), 4.2 KB.
    return crlf(numbered(90, width=40))


class LoadBench(Case):
    absolute = True

    def __init__(self, name, machine, doc, cfg=BENCH_CFG):
        self.name = name
        self.machine = machine
        self.doc = doc
        self.cfg = cfg

    def fixture(self, ctx, variant=None):
        return self.doc

    def timeline(self, ctx, variant=None):
        t = Timeline(start=0.0)
        t.snap('l0', at='LOADDOC')
        t.snap('l1', at='LOADDOC.CLSFIL')
        t.t = 300.0
        return t


class SaveBench(Case):
    def __init__(self, name, machine, doc, cfg=BENCH_CFG, wait=600.0):
        self.name = name
        self.machine = machine
        self.doc = doc
        self.cfg = cfg
        self.wait = wait

    def fixture(self, ctx, variant=None):
        return self.doc

    def timeline(self, ctx, variant=None):
        t = Timeline(start=1.0)
        t.snap('s0', at='FILESAVE')
        t.snap('s1', at='DSKCLOSE')
        t.press('S', mods=['CTRL'])
        t.wait(self.wait)
        return t


def rows():
    m, s = manual(), small()
    return [
        ('S6ED', LoadBench('bench-s6-load-manual-2mb', MACH_2MB, m)),
        ('S6ED', SaveBench('bench-s6-save-manual-2mb', MACH_2MB, m)),
        ('S6ED', LoadBench('bench-s6-load-small-128k', MACH_128K, s)),
        ('S6ED', SaveBench('bench-s6-save-small-128k', MACH_128K, s)),
        ('S62ED', LoadBench('bench-s62-load-manual-2mb', MACH_2MB, m)),
        ('S62ED', SaveBench('bench-s62-save-manual-2mb', MACH_2MB, m)),
        ('S2ED', LoadBench('bench-s2-load-manual-1mb', MACH_MSX1_1M, m,
                           S2_CFG)),
        ('S2ED', SaveBench('bench-s2-save-manual-1mb', MACH_MSX1_1M, m,
                           S2_CFG, wait=900.0)),
        ('S2ED', LoadBench('bench-s2-load-small-128k', MACH_MSX1, s, S2_CFG)),
        ('S2ED', SaveBench('bench-s2-save-small-128k', MACH_MSX1, s, S2_CFG)),
    ]


def main():
    pick = sys.argv[1] if len(sys.argv) > 1 else ''
    base = Context(HERE, load_symbols=False)
    ctxs = {}
    for target, case in rows():
        if pick not in case.name:
            continue
        ctx = ctxs.get(target)
        if ctx is None:
            ctx = ctxs[target] = base.for_target(target)
            ctx.reload_symbols()
        run = case.execute(ctx)[None]
        a, b = ('l0', 'l1') if isinstance(case, LoadBench) else ('s0', 's1')
        t0, t1 = run.var(a, 'EMUTUS'), run.var(b, 'EMUTUS')
        lines = run.var(b, 'TOTLINES')
        if t0 is None or t1 is None:
            print('%-28s  NO TIMING (%s)' % (case.name,
                  'timeout' if run.timed_out else 'snap missing'))
            continue
        note = ''
        if isinstance(case, SaveBench):
            back = run.session.extract(run.dsk, case.fixture_name)
            note = 'file OK' if back == case.doc else 'FILE DIFFERS (%s B)' % (
                len(back) if back is not None else 'none')
        print('%-28s  %9.3f s  %5s lines  %s' % (
            case.name, (t1 - t0) / 1e6, lines, note))
        sys.stdout.flush()


if __name__ == '__main__':
    main()
