"""Case definition: a disk, a timeline and a set of assertions."""

import os

from keys import Timeline
from harness import MACH_128K, Session

DEFAULT_CFG = """; generated by the S6ED test harness
PROFILE=STD
WRAP=DEV
MARKUP=OFF
CLOCK=1
TABWIDTH=4
EOL=AUTO
AUTOALIGN=DEV
THEME=DEFAULT
"""


class Case(object):
    """One openMSX session.

    Defaults to the machine that matters: a stock 128 kB Philips NMS 8250.
    The 2 MB machine hides mapper exhaustion and allocation leaks, so it is
    opt-in and only for cases that explicitly measure a ceiling.
    """

    name = 'unnamed'
    desc = ''
    origin = ''                     # the defect this case was derived from
    machine = MACH_128K
    cfg = DEFAULT_CFG
    fixture_name = 'DOC.TXT'
    with_font = True
    autoexec = None                 # defaults to "S6ED <fixture>"
    absolute = False                # True: never reaches MAINLOOP (e.g. /H),
                                    # schedule on absolute emulated time

    # A case that has to compare two code paths runs one session per variant
    # against the same build -- the only honest way to say "these are
    # equivalent" is to change nothing else.
    variants = (None,)

    def fixture(self, ctx, variant=None):
        """Bytes of the document the editor opens.  None = start with no file."""
        return None

    def config(self, ctx, variant=None):
        return self.cfg

    # - disk contents --------------------------------------------------

    def disk_files(self, ctx, variant=None):
        files = {}
        cfg = self.config(ctx, variant)
        if cfg is not None:
            files['S6ED.CFG'] = cfg
        doc = self.fixture(ctx, variant)
        if doc is not None:
            files[self.fixture_name] = doc
        cmd = self.autoexec
        if cmd is None:
            cmd = ('S6ED %s' % self.fixture_name) if doc is not None else 'S6ED'
        files['AUTOEXEC.BAT'] = cmd + '\r\n'
        return files

    def disk_copies(self, ctx):
        out = [os.path.join(ctx.code_dir, 'S6ED.COM')]
        if self.with_font:
            out.append(os.path.join(ctx.code_dir, 'S6ED.FNT'))
        return out

    # - behaviour ------------------------------------------------------

    def timeline(self, ctx, variant=None):
        raise NotImplementedError

    def verify(self, ctx, runs):
        """runs maps variant -> Run (the key is None for a single-variant case)."""
        raise NotImplementedError

    # - driving --------------------------------------------------------

    def execute(self, ctx):
        runs = {}
        for variant in self.variants:
            session = Session(ctx, self, variant)
            runs[variant] = session.run(self.timeline(ctx, variant))
        return runs


def crlf(lines):
    return ('\r\n'.join(lines) + '\r\n').encode('ascii')


def numbered(count, width=26):
    """A fixture whose every line is identifiable on sight and in a diff."""
    alpha = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    return [('LINE %05d %s' % (i, alpha[:1 + (i % width)])) for i in range(1, count + 1)]
