"""Suite S2 -- the runtime gate for the SCREEN 2 / TMS9918 target.

Every case here is derived backwards from a defect that actually shipped, the
same rule the S6 gate follows.  Two things make this suite different:

  * It runs on an MSX1 (`Custom_MSX1_DOS2` under a Nextor kernel), so the VDP
    is the one the target is written for -- including the VRAM write pacing
    that silently drops bytes when it is wrong.
  * Its verdicts are taken against a pattern table COMPUTED in Python from
    `S2ED.FNT` and the document (see pattern.py), not against a captured
    image.  A golden image blesses whatever the renderer did on the day it was
    captured; the six defects of rounds 2 and 3 would all have passed that.

S2ED reserves two mapper segments, `DIRSEG` and `FTRSEG` -- and on S2 `FTRSEG`
is also the video shadow, so on the default machine there is nothing spare
(`SEGAVL = 0`), which is the point of using it.
"""

import pattern
from cases import Case, crlf
from harness import MACH_MSX1
from keys import Timeline
from result import Check

# The shipped defaults, minus the clock.  A case whose defect is a race must
# turn the clock off or the host RTC moves MAINLOOP's phase between runs and it
# passes and fails at random (learned on D8).
S2_CFG = """; generated by the S2ED test harness
PROFILE=STD
WRAP=TXT
MARKUP=OFF
CLOCK=0
TABWIDTH=4
EOL=AUTO
AUTOALIGN=OFF
"""


class S2Case(Case):
    machine = MACH_MSX1
    cfg = S2_CFG


def one(runs):
    return runs[None]


def font(ctx):
    return pattern.load_font(ctx)


# --- S2-1  THE SCREEN IS WHAT THE DOCUMENT SAYS -----------------------


class S21Render(S2Case):
    name = 'S2-1-render'
    desc = 'every painted row matches a pattern table computed from the font'
    origin = ('round 1: RENDEROW called COMROW with B destroyed by LINEREAD s '
               'LDIR, so every text row composed on top of row 0 and what '
               'reached the screen was whatever FTRSEG held there')
    LINES = ['%02d %s' % (i, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'[:1 + i % 26])
             for i in range(40)]

    def fixture(self, ctx, variant=None):
        return crlf(self.LINES)

    def timeline(self, ctx, variant=None):
        t = Timeline()
        t.snap('boot', vram='patcol')
        return t

    def verify(self, ctx, runs):
        run = one(runs)
        dump = run.blob('boot', 'patcol')
        checks = []
        if dump is None:
            return [Check('S2-1/dump', False, 'no VRAM dump')]
        pat, col = dump[:0x2000], dump[0x2000:]
        bad = pattern.mismatched_rows(
            pat, font(ctx), self.LINES, run.var('boot', 'TOPLINE'),
            cursor=(pattern.TXRFIRST + run.var('boot', 'CURY'),
                    run.var('boot', 'CURX')))
        checks.append(Check('S2-1/rows', not bad,
                            '%d text rows match the computed table'
                            % pattern.ROWSVIS if not bad else
                            'rows differ: %s' % bad[:6]))
        checks.append(Check('S2-1/totlines',
                            run.var('boot', 'TOTLINES') == len(self.LINES),
                            'TOTLINES = %s (expected %d)'
                            % (run.var('boot', 'TOTLINES'), len(self.LINES))))
        # FTRSEG is the video shadow as well as the feature container, so a
        # boot that did not claim both segments is a different bug wearing
        # this case's clothes.
        checks.append(Check('S2-1/segments', run.var('boot', 'SEGCNT') == 2,
                            'SEGCNT = %s (DIRSEG + FTRSEG)'
                            % run.var('boot', 'SEGCNT')))
        uniform, colours = pattern.uniform_colour_cells(col, pattern.TXRFIRST)
        checks.append(Check('S2-1/colour-expand', uniform == pattern.CELLS,
                            '%d/%d cells uniform across their 8 scanlines'
                            % (uniform, pattern.CELLS)))
        return checks


# --- S2-2  ATTRIBUTES COME UP CLEAN -----------------------------------


class S22Attrs(S2Case):
    name = 'S2-2-attrs'
    desc = 'no line comes up with stray attributes (the yellow bands)'
    origin = ('round 2: CORE/FILEIO.Z8A cleared the attribute half of the '
               'record from offset 81 instead of 1 + TEXTCOLS, so the first '
               '16 attribute bytes of every record were never cleared -- '
               'mostly #FF, which COMCELL reads as ATRBOLD and paints in '
               'COLBOLD, a yellow band down the left of the line')
    LINES = ['%02d %s' % (i, 'X' * 60) for i in range(40)]

    def fixture(self, ctx, variant=None):
        return crlf(self.LINES)

    def timeline(self, ctx, variant=None):
        t = Timeline()
        t.snap('boot', vram='patcol')
        return t

    def verify(self, ctx, runs):
        run = one(runs)
        col = run.blob('boot', 'patcol')
        if col is None:
            return [Check('S2-2/dump', False, 'no VRAM dump')]
        col = col[0x2000:]
        wrong = []
        for row in range(pattern.TXRFIRST, pattern.TXRLAST + 1):
            _, colours = pattern.uniform_colour_cells(col, row)
            other = colours - {pattern.COLTXT}
            if other:
                wrong.append((row, sorted('#%02X' % c for c in other)))
        return [
            Check('S2-2/text-colour', not wrong,
                  'every text cell carries COLTXT (#F1)' if not wrong else
                  'rows with other colours: %s' % wrong[:6]),
            Check('S2-2/no-bold',
                  not any(pattern.COLBOLD in dict(wrong).get(r, [])
                          for r in range(pattern.TXRFIRST,
                                         pattern.TXRLAST + 1)),
                  'no COLBOLD anywhere in the text band'),
        ]


# --- S2-3  THE CURSOR IS ONE COLUMN WIDE ------------------------------


class S23Cursor(S2Case):
    name = 'S2-3-cursor'
    desc = 'the cursor inverts exactly one text column'
    origin = ('round 2: the cursor swapped the FG/BG nibbles of the cell s '
               'colour byte.  Screen 2 colour addresses 8x1 SLICES and a cell '
               'holds two 4 px characters, so the finest thing a colour swap '
               'can invert is two columns.  PATINV inverts the pattern bits '
               'of the four pixel columns the text column owns instead.')
    LINES = ['CURSOR ON THIS LINE', 'SECOND LINE']

    def fixture(self, ctx, variant=None):
        return crlf(self.LINES)

    # The cursor blinks: MAINLOOP toggles BLNKPH every 20 JIFFY ticks (0.4 s
    # at 50 Hz), so a single sample can catch it drawn or erased and proves
    # nothing on its own.  Two rules make this deterministic:
    #
    #   * every sample is checked AGAINST ITS OWN BLNKPH -- erased must equal
    #     the plain render, drawn must equal it with one column inverted;
    #   * the sample intervals are deliberately uneven.  The first version
    #     spaced them evenly and every one landed in the same phase: a snap
    #     costs 0.6 s and the wait was 0.22 s, so BLNKCNT advanced 40-41 ticks
    #     between samples -- exactly two toggles.  Measured, all five read
    #     BLNKPH = 0 and the case failed against a cursor that was working.
    #
    # The last sample does not rely on the free-running blink at all: a
    # keystroke ends in .DRAWCUR, which draws the cursor and sets BLNKPH = 1,
    # so LEFT + RIGHT returns to the same column with the cursor guaranteed up.
    SAMPLES = 4

    def timeline(self, ctx, variant=None):
        t = Timeline()
        t.press('RIGHT', repeat=5)
        for i in range(self.SAMPLES):
            t.snap('s%d' % i, vram='pat')
            t.wait(0.1 * i)
        t.press('LEFT')
        # A short tail on purpose: .DRAWCUR runs just after key-down, and the
        # blink toggles 20 JIFFY ticks later.  The default 0.35 s tail puts
        # the sample 30 ticks after the keystroke -- past the toggle, cursor
        # already erased.  0.05 s puts it at ~15.
        t.press('RIGHT', tail=0.05)
        t.snap('drawn', vram='pat')
        return t

    def verify(self, ctx, runs):
        run = one(runs)
        curx = run.var('s0', 'CURX')
        row = pattern.TXRFIRST + (run.var('s0', 'CURY') or 0)
        plain = pattern.compose_row(font(ctx), self.LINES[0])
        inverted = pattern.invert_column(plain, curx)

        wrong, phases = [], []
        for label in ['s%d' % i for i in range(self.SAMPLES)] + ['drawn']:
            pat = run.blob(label, 'pat')
            if pat is None:
                wrong.append('%s: no dump' % label)
                continue
            got = pattern.row_of(pat, row)
            ph = run.var(label, 'BLNKPH')
            phases.append(ph)
            want = inverted if ph == 1 else plain
            cols = pattern.differing_columns(got, want)
            if cols:
                wrong.append('%s (BLNKPH=%s): columns %s' % (label, ph, cols))

        drawn = run.var('drawn', 'BLNKPH')
        got = run.blob('drawn', 'pat')
        one_col = (pattern.differing_columns(
            pattern.row_of(got, row), plain) == [curx]) if got else False
        return [
            Check('S2-3/curx', curx == 5, 'CURX = %s (expected 5)' % curx),
            Check('S2-3/blink-exact', not wrong,
                  'all %d samples match their own blink phase exactly '
                  '(phases seen: %s)' % (len(phases), phases)
                  if not wrong else '; '.join(wrong[:4])),
            Check('S2-3/drawn-up', drawn == 1,
                  'the cursor is up after a keystroke (BLNKPH = %s)' % drawn),
            Check('S2-3/one-column', one_col,
                  'and it covers exactly one text column'
                  if one_col else 'columns differing: %s'
                  % (pattern.differing_columns(pattern.row_of(got, row), plain)
                     if got else 'no dump')),
        ]


# --- S2-4  SELECTION EXTENDS AND LEAVES NOTHING BEHIND ----------------


class S24Select(S2Case):
    name = 'S2-4-select'
    desc = 'SHIFT+RIGHT inverts every column it covers, and deselect leaves none'
    origin = ('round 2: SELDIFF extends a selection ONE COLUMN at a time, so '
               'with a cell-granularity painter two consecutive deltas landed '
               'on the same cell and their XORs cancelled -- selecting 5..11 '
               'inverted only cell 2, and deselecting left cells 3 and 4 '
               'standing as residue.  The selection engine was never broken, '
               'only the painting.')
    LINES = ['SELECT SOME OF THIS LINE PLEASE', 'SECOND LINE']

    def fixture(self, ctx, variant=None):
        return crlf(self.LINES)

    def timeline(self, ctx, variant=None):
        t = Timeline()
        t.press('RIGHT', repeat=5)
        t.snap('before', vram='pat')
        t.press('RIGHT', mods=['SHIFT'], repeat=6)
        t.snap('selected', vram='pat')
        t.press('LEFT')                     # unshifted: deselect
        t.snap('after', vram='pat')
        return t

    def verify(self, ctx, runs):
        run = one(runs)
        checks = []
        plain = pattern.compose_row(font(ctx), self.LINES[0])
        row = pattern.TXRFIRST + (run.var('selected', 'CURY') or 0)
        sel = run.blob('selected', 'pat')
        after = run.blob('after', 'pat')
        if sel is None or after is None:
            return [Check('S2-4/dump', False, 'missing VRAM dump')]
        checks.append(Check('S2-4/selact',
                            run.var('selected', 'SELACT') == 1,
                            'SELACT = %s' % run.var('selected', 'SELACT')))
        inv = pattern.inverted_columns(pattern.row_of(sel, row), plain)
        # The cursor is itself an inversion and sits at one end of the range,
        # so the inverted set is the selected columns, cursor included.
        want = list(range(5, 12))
        checks.append(Check('S2-4/range', inv == want,
                            'columns %d..%d inverted' % (want[0], want[-1])
                            if inv == want else 'inverted: %s' % inv))
        # After deselecting, only the cursor cell may differ from the document.
        curx = run.var('after', 'CURX')
        diff = pattern.differing_columns(pattern.row_of(after, row), plain)
        residue = [c for c in diff if c != curx]
        checks.append(Check('S2-4/no-residue', not residue,
                            'zero columns left inverted after deselect'
                            if not residue else 'residue at %s' % residue))
        return checks


# --- S2-5  THE CURSOR STAYS INSIDE THE TEXT BAND ----------------------


class S25Band(S2Case):
    name = 'S2-5-band'
    desc = 'the viewport scrolls at the bottom of the TEXT BAND, not the screen'
    origin = ('round 2: sixteen sites in CORE bounded the cursor with '
               'SCRROWS (24, the physical screen) where they meant ROWSVIS '
               '(22, the text band).  The cursor walked two rows below the '
               'painted band before the viewport scrolled -- from the '
               'keyboard, "the scroll does not work" -- and DRWCUR then '
               'addressed CTBASE + 24 * 256 = #3800, putting 8 bytes into '
               'the sprite generator table.')
    LINES = ['LINE %03d' % i for i in range(60)]

    def fixture(self, ctx, variant=None):
        return crlf(self.LINES)

    def timeline(self, ctx, variant=None):
        t = Timeline()
        t.press('DOWN', repeat=33)
        t.snap('descended', vram='pat')
        return t

    def verify(self, ctx, runs):
        run = one(runs)
        cury = run.var('descended', 'CURY')
        topline = run.var('descended', 'TOPLINE')
        docline = run.var('descended', 'DOCLINE')
        pat = run.blob('descended', 'pat')
        checks = [
            Check('S2-5/cury', cury == pattern.ROWSVIS - 1,
                  'CURY = %s (expected %d, the last visible row)'
                  % (cury, pattern.ROWSVIS - 1)),
            Check('S2-5/viewport', topline == docline - cury,
                  'TOPLINE %s = DOCLINE %s - CURY %s'
                  % (topline, docline, cury)),
        ]
        if pat is not None:
            bad = pattern.mismatched_rows(
                pat, font(ctx), self.LINES, topline,
                cursor=(pattern.TXRFIRST + cury,
                        run.var('descended', 'CURX')))
            checks.append(Check('S2-5/scrolled-rows', not bad,
                                'the scrolled screen matches the document'
                                if not bad else 'rows differ: %s' % bad[:6]))
        return checks


# --- S2-6  BACKSPACE, THEN KEEP TYPING --------------------------------


class S26DelType(S2Case):
    name = 'S2-6-deltype'
    desc = 'typing still works after BACKSPACE and after DEL'
    origin = ('round 3: EDDELBK and EDDELCHR ran their shift loop to a hard '
               '79 and blanked WORKBUF + 80.  On a 1+64+64 record that drags '
               'the attribute byte of column 0 into the LAST TEXT COLUMN, '
               'after which EDINSCHR sees a full record and refuses every '
               'keystroke on that line -- silently, in WRAP_DEV.  LINEWRT '
               'persists it, so the line stays poisoned.')
    LINES = ['HELLO MSX WORLD', 'SECOND LINE']
    # Both delete keys and both wrap modes.  The mode matters: in WRAP_DEV the
    # refused insert is a mute RET NZ -- the user's "it just stops typing" --
    # while in WRAP_TXT it goes to EDPSHWR and shows up as a spurious wrap
    # instead, which is why TOTLINES is asserted as well as the text.
    variants = ('bs-dev', 'del-dev', 'bs-txt', 'del-txt')

    def fixture(self, ctx, variant=None):
        return crlf(self.LINES)

    def config(self, ctx, variant=None):
        mode = 'DEV' if variant.endswith('-dev') else 'TXT'
        return self.cfg.replace('WRAP=TXT', 'WRAP=' + mode)

    def timeline(self, ctx, variant=None):
        t = Timeline()
        for k in 'LABEL':
            t.press(k)
        t.snap('typed')
        t.press('BS' if variant.startswith('bs') else 'DEL', repeat=3)
        t.snap('deleted')
        t.press('X')
        t.press('S', mods=['CTRL'])
        t.wait(3.0)
        t.snap('saved', vram='pat')
        return t

    def verify(self, ctx, runs):
        checks = []
        for variant, run in sorted(runs.items()):
            # keymatrixdown without SHIFT delivers lowercase.
            head = self.LINES[0]
            if variant.startswith('bs'):
                want_first = 'la' + 'x' + head       # 5 typed, 3 removed
            else:
                want_first = 'label' + 'x' + head[3:]  # DEL eats 3 ahead
            typed = run.var('typed', 'CURX')
            checks.append(Check('S2-6/%s/typed' % variant, typed == 5,
                                'CURX = %s after typing LABEL' % typed))
            got = run.session.extract(run.dsk, 'DOC.TXT')
            first = (got or b'').split(b'\r\n')[0].decode('ascii', 'replace')
            tot = run.var('saved', 'TOTLINES')
            checks.append(Check('S2-6/%s/totlines' % variant,
                                tot == len(self.LINES),
                                'TOTLINES = %s (expected %d: nothing wrapped)'
                                % (tot, len(self.LINES))))
            checks.append(Check('S2-6/%s/line' % variant, first == want_first,
                                'line reads %r' % first if first == want_first
                                else 'line reads %r, expected %r'
                                     % (first, want_first)))
            pat = run.blob('saved', 'pat')
            if pat is not None:
                lines = [want_first] + self.LINES[1:]
                bad = pattern.mismatched_rows(
                    pat, font(ctx), lines, run.var('saved', 'TOPLINE'),
                    cursor=(pattern.TXRFIRST + run.var('saved', 'CURY'),
                            run.var('saved', 'CURX')))
                checks.append(Check('S2-6/%s/screen' % variant, not bad,
                                    'screen agrees with the document'
                                    if not bad else 'rows differ: %s' % bad[:4]))
        return checks


# --- S2-7  ENTER ON THE LAST VISIBLE ROW ------------------------------


class S27EnterBot(S2Case):
    name = 'S2-7-enterbot'
    desc = 'splitting on the last visible row repaints the head, not the status bar'
    origin = ('round 3: EDNWLIN repainted the shortened head with a literal '
               'LD B, 23 -- the row below the last visible one on S2, which '
               'is the STATUS BAR.  The head at row 21 was left stale and the '
               'status bar was painted over with document text.')
    LINES = ['LINE %03d ABCDEFGHIJ' % i for i in range(40)]

    def fixture(self, ctx, variant=None):
        return crlf(self.LINES)

    def timeline(self, ctx, variant=None):
        t = Timeline()
        t.press('DOWN', repeat=25)          # well past the bottom of the band
        t.press('RIGHT', repeat=4)          # split mid-line
        t.snap('atbottom', vram='patcol')
        t.press('RETURN')
        t.snap('split', vram='patcol')
        t.press('S', mods=['CTRL'])
        t.wait(3.0)
        t.snap('saved')
        return t

    def verify(self, ctx, runs):
        run = one(runs)
        before = run.blob('atbottom', 'patcol')
        after = run.blob('split', 'patcol')
        if before is None or after is None:
            return [Check('S2-7/dump', False, 'missing VRAM dump')]
        checks = [
            Check('S2-7/at-band-bottom',
                  run.var('atbottom', 'CURY') == pattern.ROWSVIS - 1,
                  'CURY = %s before the split'
                  % run.var('atbottom', 'CURY')),
            Check('S2-7/totlines',
                  run.var('split', 'TOTLINES') == len(self.LINES) + 1,
                  'TOTLINES = %s (expected %d)'
                  % (run.var('split', 'TOTLINES'), len(self.LINES) + 1)),
        ]
        # The status bar is chrome.  It may legitimately change (the modified
        # marker), but it must still be CHROME: with LD B, 23 the split
        # painted a document line there, in COLTXT.  Since the chrome split
        # the bar has its own role, VCOLSTAT, distinct from the menu bar's.
        _, colours = pattern.uniform_colour_cells(after[0x2000:],
                                                  pattern.STBROW)
        checks.append(Check(
            'S2-7/status-is-chrome', colours == {pattern.COLSTAT},
            'the status bar is still painted in COLSTAT (#%02X)'
            % pattern.COLSTAT if colours == {pattern.COLSTAT} else
            'status bar colours: %s' % sorted('#%02X' % c for c in colours)))
        head_row = pattern.row_of(after[:0x2000], pattern.STBROW)
        band_row = pattern.row_of(after[:0x2000], pattern.TXRLAST)
        checks.append(Check(
            'S2-7/status-not-text', head_row != band_row,
            'the status bar does not carry a copy of a document row'))
        # And the whole band must agree with the document that was saved.
        got = run.session.extract(run.dsk, 'DOC.TXT')
        lines = (got or b'').decode('ascii', 'replace').split('\r\n')
        while lines and lines[-1] == '':
            lines.pop()
        bad = pattern.mismatched_rows(
            after[:0x2000], font(ctx), lines, run.var('split', 'TOPLINE'),
            cursor=(pattern.TXRFIRST + run.var('split', 'CURY'),
                    run.var('split', 'CURX')))
        checks.append(Check('S2-7/head-repainted', not bad,
                            'every band row agrees with the saved document'
                            if not bad else 'rows differ: %s' % bad[:6]))
        return checks


# --- S2-8  DIFFERENTIAL PAINTERS AGREE WITH A FULL REDRAW -------------


class S28RenderPure(S2Case):
    name = 'S2-8-renderpure'
    desc = 'after a burst of edits the screen equals a full REDRAW of the document'
    origin = ('the G7 idea, which is the one general case in the S6 gate: a '
               'REDRAW repaints from the document alone, so forcing one and '
               'diffing tests every differential painter at once.  Here it is '
               'checked BOTH ways -- against the REDRAW and against the '
               'computed table -- so a renderer that is consistently wrong '
               'still fails.')
    LINES = ['ROW %03d %s' % (i, 'abcdefghijklmnop') for i in range(30)]

    def fixture(self, ctx, variant=None):
        return crlf(self.LINES)

    # The edits end with a SPLIT, deliberately.  The first version ended with
    # BACKSPACE at column 0, which in WRAP_TXT cascades REFLOW and finishes
    # with a full REDRAW -- repainting the whole screen microseconds before
    # the sample and blinding the case: a mutation that dropped SHIFTDNN's
    # VRAM push went clean through it.  A mid-document Enter uses SHIFTDN and
    # two RENDEROW calls and repaints nothing else, so whatever those leave
    # behind is still on screen when 'edited' is taken.
    def timeline(self, ctx, variant=None):
        t = Timeline()
        t.press('DOWN', repeat=3)
        t.press('RIGHT', repeat=5)
        for k in 'ZZ':
            t.press(k)                  # in-line insert  -> RENDIFF
        t.press('BS')                   # in-line delete  -> RENDIFF
        t.press('DEL', repeat=2)
        t.press('DOWN', repeat=2)
        t.press('RIGHT', repeat=4)
        t.press('RETURN')               # mid-document split -> SHIFTDN
        t.press('S', mods=['CTRL'])
        t.wait(3.0)
        t.snap('edited', vram='patcol')
        # GRAPH+DOWN / GRAPH+UP page down and back: the viewport returns to
        # where it was and the screen is repainted wholesale on the way.
        t.press('DOWN', mods=['GRAPH'])
        t.press('UP', mods=['GRAPH'])
        t.snap('redrawn', vram='patcol')
        return t

    def verify(self, ctx, runs):
        run = one(runs)
        a, b = run.blob('edited', 'patcol'), run.blob('redrawn', 'patcol')
        if a is None or b is None:
            return [Check('S2-8/dump', False, 'missing VRAM dump')]
        same_state = all(run.var('edited', k) == run.var('redrawn', k)
                         for k in ('TOPLINE', 'DOCLINE', 'CURX', 'CURY',
                                   'TOTLINES'))
        checks = [Check('S2-8/same-state', same_state,
                        'the page round trip returned to the same position')]
        if not same_state:
            checks.append(Check('S2-8/render-pure', False,
                                'state mismatch before diff'))
            return checks
        cury = run.var('edited', 'CURY')
        rows = [r for r in range(pattern.ROWS)
                if pattern.row_of(a[:0x2000], r) != pattern.row_of(b[:0x2000], r)
                and r != pattern.TXRFIRST + cury]
        checks.append(Check('S2-8/render-pure', not rows,
                            'screen identical to a full REDRAW'
                            if not rows else 'rows differ: %s' % rows))
        got = run.session.extract(run.dsk, 'DOC.TXT')
        lines = (got or b'').decode('ascii', 'replace').split('\r\n')
        while lines and lines[-1] == '':
            lines.pop()
        bad = pattern.mismatched_rows(
            b[:0x2000], font(ctx), lines, run.var('redrawn', 'TOPLINE'),
            cursor=(pattern.TXRFIRST + cury, run.var('redrawn', 'CURX')))
        checks.append(Check('S2-8/matches-document', not bad,
                            'and it agrees with the document on disk'
                            if not bad else 'rows differ: %s' % bad[:6]))
        return checks


# --- S2-9  THE RIGHT MARGIN -------------------------------------------


class S29Margin(S2Case):
    name = 'S2-9-margin'
    desc = 'an edit at the right margin of a FULL line is an append'
    origin = ('the same CORE defect D11-margin covers, seen on the 64-column '
               'record and with the screen checked as well as the document: '
               'the cursor cannot park past the last column of a full line, '
               'so an edit taken at the clamped column landed one place too '
               'early -- typing X on a line ending in HELLO wrapped it as '
               '"HELLxO", and a space at the margin carried the "O" down.')
    TAIL = 'HELLO'
    LINE = 'A' * (pattern.COLS - len(TAIL) - 1) + ' ' + TAIL
    LINES = [LINE, 'SECOND LINE']
    variants = ('push', 'space')

    def fixture(self, ctx, variant=None):
        return crlf(self.LINES)

    def timeline(self, ctx, variant=None):
        t = Timeline()
        t.press('RIGHT', mods=['CTRL'])         # ACEOL: clamps to COLS - 1
        t.snap('ateol')
        t.press('X' if variant == 'push' else 'SPACE')
        t.press('S', mods=['CTRL'])
        t.wait(3.0)
        t.snap('done', vram='pat')
        return t

    def verify(self, ctx, runs):
        checks = []
        for variant, run in sorted(runs.items()):
            pre = 'S2-9/%s' % variant
            checks.append(Check('%s/clamped' % pre,
                                run.var('ateol', 'CURX') == pattern.COLS - 1,
                                'ACEOL leaves CURX = %s on a full line'
                                % run.var('ateol', 'CURX')))
            if variant == 'push':
                want = [self.LINE[:pattern.COLS - len(self.TAIL)],
                        self.TAIL + 'x', 'SECOND LINE']
                curx = len(self.TAIL) + 1
            else:
                want = [self.LINE, '', 'SECOND LINE']
                curx = 0
            got = run.session.extract(run.dsk, 'DOC.TXT')
            lines = (got or b'').decode('ascii', 'replace').split('\r\n')
            while lines and lines[-1] == '':
                lines.pop()
            checks.append(Check('%s/content' % pre, lines == want,
                                'document breaks correctly' if lines == want
                                else 'got %r' % (lines[:2],)))
            checks.append(Check('%s/curx' % pre,
                                run.var('done', 'CURX') == curx,
                                'CURX = %s (expected %d)'
                                % (run.var('done', 'CURX'), curx)))
            pat = run.blob('done', 'pat')
            if pat is not None:
                bad = pattern.mismatched_rows(
                    pat, font(ctx), want, run.var('done', 'TOPLINE'),
                    cursor=(pattern.TXRFIRST + run.var('done', 'CURY'), curx))
                checks.append(Check('%s/screen' % pre, not bad,
                                    'the screen shows the broken text'
                                    if not bad else 'rows differ: %s' % bad[:4]))
        return checks


# --- S2-10  THEMES RECOLOR TEXT AND CHROME ------------------------------


class S210Theme(S2Case):
    name = 'S2-10-theme'
    desc = 'each theme fills all twelve role bytes and every one reaches VRAM'
    origin = ('the theme integration itself: the TMS9918 palette is fixed, '
              'so a theme is a choice of WHICH of the 16 colours fills each '
              'role, carried in twelve RAM bytes.  THMLOAD plants the '
              'default, PARSTHM rewrites them on THEME=, and COMCELL, '
              'CLRROW, INITCOL, DRWSTAT, DRWMENU and WBOX read them instead '
              'of immediates.  A copy that never lands leaves the editor in '
              'the default theme with the config claiming otherwise -- and '
              'PARSTHM dispatches on the FIRST LETTER of the value, which is '
              'how AUTOALIGN=OFF once turned auto-align on, so MSX (index 12) '
              'only resolves because the index table reaches M.')
    # TXT, UI, BOLD, ITAL, UNDR, MARK, BORDER, STAT, WIN, HI, BSEL, SHDW
    THEMES = {
        'amber': [0xA1, 0xA6, 0xB1, 0x71, 0x31, 0xE1, 1,
                  0xA6, 0xA6, 0xB6, 0x6B, 0x66],      # S2THMBR
        'msx':   [0xF4, 0xF5, 0xB4, 0x74, 0x34, 0xE4, 4,
                  0xF5, 0xF5, 0xB5, 0x5B, 0x11],      # S2THMSX
    }
    variants = ('amber', 'msx')
    LINES = ['THEME ON THIS LINE', 'SECOND LINE']

    def fixture(self, ctx, variant=None):
        return crlf(self.LINES)

    def config(self, ctx, variant=None):
        return self.cfg + 'THEME=%s\n' % variant.upper()

    def timeline(self, ctx, variant=None):
        t = Timeline()
        t.snap('boot', vram='patcol', vars_=[('RG7SAV', 1)])
        return t

    def verify(self, ctx, runs):
        checks = []
        for variant, run in sorted(runs.items()):
            want = self.THEMES[variant]
            tag = 'S2-10/%s' % variant
            dump = run.blob('boot', 'patcol')
            if dump is None:
                checks.append(Check(tag + '/dump', False, 'no VRAM dump'))
                continue
            got = run.var('boot', 'VCOLTXT')
            checks.append(Check(tag + '/vars', got == want,
                                'all twelve role bytes hold the theme'
                                if got == want else
                                'roles = %s (expected %s)'
                                % (got, ['#%02X' % b for b in want])))
            border = run.var('boot', 'RG7SAV')
            checks.append(Check(tag + '/border', border == want[6],
                                'R#7 border = %s (expected %d)'
                                % (border, want[6])))
            col = dump[0x2000:]
            # Each role that reaches the screen at boot, on the rows it owns.
            for label, rows, role in (
                    ('text', range(pattern.TXRFIRST, pattern.TXRLAST + 1), 0),
                    ('menu', [pattern.MNUROW], 1),
                    ('status', [pattern.STBROW], 7)):
                wrong = []
                for row in rows:
                    _, colours = pattern.uniform_colour_cells(col, row)
                    if colours != {want[role]}:
                        wrong.append((row, sorted('#%02X' % c
                                                  for c in colours)))
                checks.append(Check('%s/%s' % (tag, label), not wrong,
                                    '%s is #%02X' % (label, want[role])
                                    if not wrong else 'rows: %s' % wrong[:4]))
            # The chrome roles are free to share a colour -- in every shipped
            # theme they do, because S6ED's menu bar, status bar and window
            # body are all COL_UI.  What must hold is that chrome is not the
            # document surface, or the role checks above are vacuous and the
            # mutations that swap a chrome role for VCOLTXT prove nothing.
            split = want[1] != want[0] and want[7] != want[0]
            checks.append(Check(tag + '/chrome-not-doc', split,
                                'chrome #%02X is not the document #%02X'
                                % (want[1], want[0])))
            # A shadow whose colour matches the document background is not a
            # shadow at all -- it is what #11 was on every theme but MSX.
            docbg = want[0] & 0x0F
            shadow = want[11]
            checks.append(Check(tag + '/shadow-visible',
                                (shadow & 0x0F) != docbg,
                                'shadow #%02X shows against the document '
                                'background %d' % (shadow, docbg)))
        return checks


# --- S2-11  THE ABOUT DIALOG OPENS AND LEAVES NOTHING BEHIND ------------


class S211About(S2Case):
    name = 'S2-11-about'
    desc = ('F5 opens the About dialog through the FTRBASE window engine, '
            'and closing it restores the screen byte for byte')
    origin = ('phase W1 of the S2 window engine (DEV/SPEC_S2ED_WINDOW_MENU.md): '
              'with no command engine and no off-screen VRAM, windows compose '
              'in the RAM shadows and the background is saved to a buffer at '
              'the top of FTRBASE.  A save or restore off by one cell leaves '
              'the document under the dialog permanently corrupted.')
    LINES = ['%02d %s' % (i, 'WINDOW ENGINE TEST LINE ABCDEFGHIJ')
             for i in range(10)]
    # DOABT geometry in S2/WINDOW.Z8A, in cell units
    WINR, WINC, WINNR, WINNC = 6, 9, 11, 13
    # The OK button: "[  OK  ]" at row 15, char col 27 -> cells 13..17
    BTNROW, BTNC0, BTNC1 = 15, 13, 17

    def fixture(self, ctx, variant=None):
        return crlf(self.LINES)

    def timeline(self, ctx, variant=None):
        t = Timeline()
        t.snap('boot', vram='patcol')
        t.press('F5')                           # HELP entry -> About (W1 wiring)
        t.snap('dialog', vram='patcol', at='WINPOLL')
        t.press('RETURN')
        t.snap('closed', vram='patcol')
        return t

    def want_colour(self, row, cell):
        """The role that owns one cell of the dialog, in the DARK theme."""
        if row == self.WINR:
            return pattern.COLHI            # title bar
        if row == self.BTNROW and self.BTNC0 <= cell <= self.BTNC1:
            return pattern.COLBSEL          # the focused button: inverse accent
        return pattern.COLWIN

    def cells_of(self, dump, row, cells):
        """The set of colour bytes each cell carries across its 8 scanlines."""
        crow = pattern.colour_row(dump[0x2000:], row)
        return [set(crow[c * 8:(c + 1) * 8]) for c in cells]

    def text_cells(self, fnt, text):
        """Expected pattern bytes of `text`, one 8-byte cell per char pair."""
        high, low = fnt
        out = []
        for i in range(0, len(text), 2):
            l, r = ord(text[i]), ord(text[i + 1])
            out.append(bytes(high[l * 8 + y] | low[r * 8 + y]
                             for y in range(8)))
        return out

    def verify(self, ctx, runs):
        run = one(runs)
        boot = run.blob('boot', 'patcol')
        dlg = run.blob('dialog', 'patcol')
        closed = run.blob('closed', 'patcol')
        if boot is None or dlg is None or closed is None:
            return [Check('S2-11/dump', False, 'missing VRAM dump')]
        checks = [
            Check('S2-11/winactv-open',
                  run.var('dialog', 'WINACTV') == 1,
                  'WINACTV = %s while the dialog is open'
                  % run.var('dialog', 'WINACTV')),
            Check('S2-11/winactv-closed',
                  run.var('closed', 'WINACTV') == 0,
                  'WINACTV = %s after the dialog closes'
                  % run.var('closed', 'WINACTV')),
        ]

        # Three chrome roles share the dialog, as in S6ED: the accent
        # (VCOLHI) carries the title bar, the focus role (VCOLBSEL) the
        # button -- a TMS9918 cell is one FG|BG byte, so focus cannot be a
        # border drawn inside it and is the inverse accent instead -- and
        # the body role (VCOLWIN) everything else.  None is VCOLTXT, which
        # is what makes a dialog a surface and not a patch of document.
        bad = [(r, c) for r in range(self.WINR, self.WINR + self.WINNR)
               for c, v in enumerate(self.cells_of(dlg, r, range(
                   self.WINC, self.WINC + self.WINNC)), start=self.WINC)
               if v != {self.want_colour(r, c)}]
        checks.append(Check('S2-11/window-colour', not bad,
                            'body #%02X, title bar #%02X, focused button '
                            '#%02X' % (pattern.COLWIN, pattern.COLHI,
                                       pattern.COLBSEL) if not bad else
                            'cells with wrong colour: %s' % bad[:6]))

        # The shadow margin: right column rows WINR+1..WINR+WINNR and bottom
        # row cells WINC+1..WINC+WINNC, all VCOLSHDW.  The shadow is a theme
        # role, not a constant: it keeps the document's pattern and flattens
        # its colour, so a black shadow is invisible on the three themes
        # whose document is black.
        bad = [(r, self.WINC + self.WINNC)
               for r in range(self.WINR + 1, self.WINR + self.WINNR + 1)
               for v in self.cells_of(dlg, r, [self.WINC + self.WINNC])
               if v != {pattern.COLSHDW}]
        bad += [(self.WINR + self.WINNR, c)
                for c, v in enumerate(self.cells_of(
                    dlg, self.WINR + self.WINNR,
                    range(self.WINC + 1, self.WINC + self.WINNC + 1)),
                    start=self.WINC + 1)
                if v != {pattern.COLSHDW}]
        checks.append(Check('S2-11/shadow', not bad,
                            'right and bottom shadow cells are #%02X'
                            % pattern.COLSHDW
                            if not bad else 'cells not shadowed: %s'
                            % bad[:6]))

        # The title cuts the top edge: "About S2ED" at row WINR, one cell in.
        # Scanline 7 of the whole row belongs to the separator, which is laid
        # down after the title, so the glyph owns scanlines 0..6 only.
        fnt = font(ctx)
        trow = pattern.row_of(dlg[:0x2000], self.WINR)
        bad = [self.WINC + 1 + i
               for i, want in enumerate(self.text_cells(fnt, 'About S2ED'))
               if trow[(self.WINC + 1 + i) * 8:(self.WINC + 2 + i) * 8]
               != want[:7] + b'\xff']
        checks.append(Check('S2-11/title-text', not bad,
                            'title "About S2ED" rendered from the RAM font'
                            if not bad else 'title cells differ: %s' % bad))

        # Body line: "S2ED - MSX1 64-Col" at row WINR+2, char col 20
        brow = pattern.row_of(dlg[:0x2000], self.WINR + 2)
        bad = [10 + i
               for i, want in enumerate(self.text_cells(
                   fnt, 'S2ED - MSX1 64-Col'))
               if brow[(10 + i) * 8:(11 + i) * 8] != want]
        checks.append(Check('S2-11/body-text', not bad,
                            'body "S2ED - MSX1 64-Col" rendered'
                            if not bad else 'body cells differ: %s' % bad))

        # The frame, pattern level.  Top edge: #FF on scanline 0 of every
        # window cell EXCEPT the ones the title occupies, which carry the
        # glyphs' scanline 0 (the clear behind the title must span exactly
        # the title cells, not the whole inner edge)
        tcells = self.text_cells(fnt, 'About S2ED')
        bad = []
        for c in range(self.WINC, self.WINC + self.WINNC):
            i = c - (self.WINC + 1)
            want = tcells[i][0] if 0 <= i < len(tcells) else 0xFF
            got = trow[c * 8]
            if got != want:
                bad.append((c, '#%02X' % got))
        checks.append(Check('S2-11/top-edge', not bad,
                            'top edge is #FF on scanline 0 except behind '
                            'the title' if not bad else
                            'top-edge cells differ: %s' % bad[:6]))

        # Side borders: #C0 left, #03 right, on every row.  The corner cells
        # are the union with the edges: the top edge owns their scanline 0
        # and the bottom edge their scanline 7
        bad = []
        for r in range(self.WINR, self.WINR + self.WINNR):
            prow = pattern.row_of(dlg[:0x2000], r)
            for c, v in [(self.WINC, 0xC0), (self.WINC + self.WINNC - 1, 0x03)]:
                want = bytearray([v] * 8)
                if r == self.WINR:
                    want[0] = 0xFF      # top edge
                    want[7] = 0xFF      # separator under the title bar
                if r == self.WINR + self.WINNR - 1:
                    want[7] = 0xFF
                if prow[c * 8:(c + 1) * 8] != bytes(want):
                    bad.append((r, c))
        checks.append(Check('S2-11/side-borders', not bad,
                            'left border #C0, right border #03 on every row'
                            if not bad else 'border cells differ: %s'
                            % bad[:6]))

        # The separator that closes the title bar: scanline 7 of every cell
        # of the top row, borders included.  It is drawn after the title
        # because WINPUTC overwrites all eight scanlines of a cell, so a
        # line laid down first would survive everywhere except under the
        # title -- which is the half anyone would notice.
        bad = [c for c in range(self.WINC, self.WINC + self.WINNC)
               if trow[c * 8 + 7] != 0xFF]
        checks.append(Check('S2-11/title-separator', not bad,
                            'a separator closes the title bar across the '
                            'window' if not bad else
                            'cells without the separator: %s' % bad[:6]))

        # Bottom edge: #FF on scanline 7 of every cell of the last row
        frow = pattern.row_of(dlg[:0x2000], self.WINR + self.WINNR - 1)
        bad = [c for c in range(self.WINC, self.WINC + self.WINNC)
               if frow[c * 8 + 7] != 0xFF]
        checks.append(Check('S2-11/bottom-edge', not bad,
                            'bottom edge is #FF on scanline 7 across the '
                            'window' if not bad else
                            'bottom-edge cells differ: %s' % bad[:6]))

        # The corner cells outside the window and its shadow -- (WINR,
        # WINC+WINNC) above the right shadow column and (WINR+WINNR, WINC)
        # left of the bottom strip -- stay untouched document
        bad = []
        for r, c in [(self.WINR, self.WINC + self.WINNC),
                     (self.WINR + self.WINNR, self.WINC)]:
            sl = slice(c * 8, (c + 1) * 8)
            if (pattern.row_of(dlg, r)[sl] != pattern.row_of(boot, r)[sl]
                    or pattern.colour_row(dlg[0x2000:], r)[sl]
                    != pattern.colour_row(boot[0x2000:], r)[sl]):
                bad.append((r, c))
        checks.append(Check('S2-11/corners-untouched', not bad,
                            'corner cells outside the window are byte-'
                            'identical to boot' if not bad else
                            'corners differ: %s' % bad))

        # Global guard: outside the window rect and the shadow margin the
        # dialog is the boot screen byte for byte, patterns AND colours --
        # and inside the shadow only the colours may change (a shadow
        # darkens, it does not repaint).  The blinking cursor column is the
        # one legitimate diff.
        currow = pattern.TXRFIRST + (run.var('dialog', 'CURY') or 0)
        curcol = run.var('dialog', 'CURX') or 0
        bad = []
        for row in range(pattern.ROWS):
            dpat, bpat = pattern.row_of(dlg, row), pattern.row_of(boot, row)
            dcol = pattern.colour_row(dlg[0x2000:], row)
            bcol = pattern.colour_row(boot[0x2000:], row)
            for cell in range(pattern.CELLS):
                if (self.WINR <= row < self.WINR + self.WINNR
                        and self.WINC <= cell < self.WINC + self.WINNC):
                    continue                # window rect: checked above
                sl = slice(cell * 8, (cell + 1) * 8)
                patdiff = dpat[sl] != bpat[sl]
                coldiff = dcol[sl] != bcol[sl]
                inshdw = (cell == self.WINC + self.WINNC
                          and self.WINR + 1 <= row
                          <= self.WINR + self.WINNR) or \
                         (row == self.WINR + self.WINNR
                          and self.WINC + 1 <= cell
                          <= self.WINC + self.WINNC)
                if inshdw:
                    if patdiff:             # colours checked by S2-11/shadow
                        bad.append((row, cell))
                    continue
                if not (patdiff or coldiff):
                    continue
                if row == currow and curcol // 2 == cell and not coldiff:
                    inv = pattern.invert_column(bpat, curcol)
                    if dpat[sl] in (bpat[sl], inv[sl]):
                        continue            # cursor up or down at the snap
                bad.append((row, cell))
        checks.append(Check('S2-11/outside-untouched', not bad,
                            'outside the window and shadow the screen is '
                            'untouched, and the shadow repaints no patterns'
                            if not bad else 'cells differ: %s' % bad[:6]))

        # Restore: identical to boot, except the blinking cursor column
        currow = pattern.TXRFIRST + (run.var('closed', 'CURY') or 0)
        curcol = run.var('closed', 'CURX') or 0
        bad = []
        for row in range(pattern.ROWS):
            cols = pattern.differing_columns(pattern.row_of(closed, row),
                                             pattern.row_of(boot, row))
            cols = [c for c in cols
                    if not (row == currow and c == curcol)]
            if cols:
                bad.append((row, cols))
        checks.append(Check('S2-11/restore-patterns', not bad,
                            'patterns restored byte for byte' if not bad else
                            'stray cells: %s' % bad[:6]))
        checks.append(Check('S2-11/restore-colours',
                            closed[0x2000:] == boot[0x2000:],
                            'colour table restored byte for byte'))
        return checks


# --- S2-12  A DIALOG MUST NOT EAT THE UNDO RING -----------------------


class S212DialogUndo(S2Case):
    name = 'S2-12-dialog-undo'
    desc = 'opening and closing the About dialog leaves the undo ring intact'
    origin = ('2026-09-22: the window background save buffer moved out of the '
              'feature container into the TPA, above the undo ring.  The two '
              'are now neighbours in page 1, and a buffer placed by hand '
              'instead of by the chain lands on top of the ring -- silently, '
              'because the dialog itself still opens and restores perfectly.  '
              'The static tpa-chain check forbids fixed addresses; only a run '
              'can prove the two allocations do not overlap.')
    LINES = ['HELLO MSX WORLD', 'SECOND LINE']

    def fixture(self, ctx, variant=None):
        return crlf(self.LINES)

    def timeline(self, ctx, variant=None):
        t = Timeline()
        t.text('PREFIX ')                       # one coalesced transaction
        t.snap('typed')
        t.press('F5')                           # About, through FTRBASE
        t.snap('dialog', at='WINPOLL')
        t.press('RETURN')
        t.snap('closed')
        t.press('Z', mods=['CTRL'])             # undo the burst
        t.snap('undone', vram='pat')
        t.press('S', mods=['CTRL'])
        t.wait(3.0)
        t.snap('saved')
        return t

    def verify(self, ctx, runs):
        run = one(runs)
        typed_x = run.var('typed', 'CURX')
        checks = [
            Check('S2-12/typed', typed_x == 7 and run.var('typed', 'UNDOPTR'),
                  'CURX = %s and a transaction is open after typing'
                  % typed_x),
        ]

        # The dialog is not an edit: it may not move the ring at all.
        ring = ('UNDOPTR', 'UNDONXT', 'UNDOBOT')
        moved = [v for v in ring
                 if run.var('typed', v) != run.var('closed', v)]
        checks.append(Check('S2-12/ring-intact', not moved,
                            'the ring pointers survive the dialog'
                            if not moved else
                            'the dialog moved %s' % ', '.join(moved)))

        undone_x = run.var('undone', 'CURX')
        checks.append(Check('S2-12/undone', undone_x == 0,
                            'CURX = %s after Undo' % undone_x))

        got = run.session.extract(run.dsk, 'DOC.TXT')
        want = crlf(self.LINES)
        checks.append(Check('S2-12/content', got == want,
                            'the document is the original byte for byte'
                            if got == want else 'got %r, want %r'
                            % (got, want)))

        pat = run.blob('undone', 'pat')
        if pat is None:
            checks.append(Check('S2-12/screen', False, 'missing VRAM dump'))
        else:
            bad = pattern.mismatched_rows(
                pat, font(ctx), self.LINES, run.var('undone', 'TOPLINE'),
                cursor=(pattern.TXRFIRST + run.var('undone', 'CURY'),
                        run.var('undone', 'CURX')))
            checks.append(Check('S2-12/screen', not bad,
                                'the screen agrees with the undone document'
                                if not bad else 'rows differ: %s' % bad[:4]))
        return checks


# --- S2-13  THE SHADOW= CONFIG KEY ------------------------------------


class S213ShadowCfg(S2Case):
    name = 'S2-13-shadow'
    desc = 'SHADOW=OFF leaves the margin alone, SHADOW=<hex> repaints it'
    origin = ('the drop shadow was a hardcoded #11, black ink on black.  A '
              'shadow cell keeps the document pattern and only flattens its '
              'colour, so it reads as a shadow exactly where it differs from '
              'the document background -- which was true of one theme out of '
              'four and nobody noticed until MSX existed to compare against.  '
              'It is a theme role now, and this is the key that overrides it.')
    WINR, WINC, WINNR, WINNC = 6, 9, 11, 13     # DOABT, in cells
    LINES = ['%02d %s' % (i, 'SHADOW TEST LINE ABCDEFGHIJKLMNOP')
             for i in range(12)]
    variants = ('off', 'colour')

    def fixture(self, ctx, variant=None):
        return crlf(self.LINES)

    def config(self, ctx, variant=None):
        return self.cfg + ('SHADOW=OFF\n' if variant == 'off'
                           else 'SHADOW=C\n')

    def timeline(self, ctx, variant=None):
        t = Timeline()
        t.snap('boot', vram='patcol')
        t.press('F5')
        t.snap('dialog', vram='patcol', at='WINPOLL')
        return t

    def margin(self):
        """The cells the drop shadow owns: right column and bottom row."""
        return ([(r, self.WINC + self.WINNC)
                 for r in range(self.WINR + 1, self.WINR + self.WINNR + 1)] +
                [(self.WINR + self.WINNR, c)
                 for c in range(self.WINC + 1, self.WINC + self.WINNC + 1)])

    def verify(self, ctx, runs):
        checks = []
        for variant, run in sorted(runs.items()):
            tag = 'S2-13/%s' % variant
            boot = run.blob('boot', 'patcol')
            dlg = run.blob('dialog', 'patcol')
            if boot is None or dlg is None:
                checks.append(Check(tag + '/dump', False, 'missing VRAM dump'))
                continue
            bad = []
            for r, c in self.margin():
                sl = slice(c * 8, (c + 1) * 8)
                got = pattern.colour_row(dlg[0x2000:], r)[sl]
                if variant == 'off':
                    # Untouched: the document's own colours, still there.
                    if got != pattern.colour_row(boot[0x2000:], r)[sl]:
                        bad.append((r, c))
                elif set(got) != {0xCC}:
                    bad.append((r, c, sorted('#%02X' % b for b in set(got))))
            checks.append(Check(
                tag + '/margin', not bad,
                'the margin keeps the document colours'
                if variant == 'off' else
                'every margin cell is #CC (SHADOW=C, flattened)'
                if not bad else 'cells differ: %s' % bad[:6]))

            # Whatever the key says, the patterns under the margin are the
            # document's: a shadow recolours, it never repaints.
            bad = [(r, c) for r, c in self.margin()
                   if pattern.row_of(dlg, r)[c * 8:(c + 1) * 8]
                   != pattern.row_of(boot, r)[c * 8:(c + 1) * 8]]
            checks.append(Check(tag + '/patterns', not bad,
                                'the margin repaints no patterns'
                                if not bad else 'cells differ: %s' % bad[:6]))
        return checks


CASES = [S21Render(), S22Attrs(), S23Cursor(), S24Select(), S25Band(),
         S26DelType(), S27EnterBot(), S28RenderPure(), S29Margin(),
         S210Theme(), S211About(), S212DialogUndo(),
         S213ShadowCfg()]


def run(ctx, cases=None):
    """Execute the S2 gate against an S2ED context.  Same shape as gate.run."""
    checks = []
    for case in (cases if cases is not None else CASES):
        try:
            runs = case.execute(ctx)
        except Exception as exc:                          # noqa: BLE001
            checks.append(Check(case.name, False, 'harness error: %s' % exc))
            continue
        broken = [v for v, r in runs.items()
                  if r.timed_out or 'DONE' not in r.lines]
        if broken:
            checks.append(Check(case.name, False,
                                'session did not finish: %s'
                                % ', '.join(str(v) for v in broken)))
            continue
        try:
            checks += case.verify(ctx, runs)
        except Exception as exc:                          # noqa: BLE001
            checks.append(Check(case.name, False,
                                'verify error: %s: %s'
                                % (type(exc).__name__, exc)))
    return checks
