"""Suite S2 -- the runtime gate for the SCREEN 2 / TMS9918 target.

Every case here is derived backwards from a defect that actually shipped, the
same rule the S6 gate follows.  Two things make this suite different:

  * It runs on an MSX1 (`Custom_MSX1_DOS2` under a Nextor kernel), so the VDP
    is the one the target is written for -- including the VRAM write pacing
    that silently drops bytes when it is wrong.
  * Its verdicts are taken against a pattern table COMPUTED in Python from
    `S2ED.FNT` and the document (see pattern.py), not against a captured
    image.  A golden image blesses whatever the renderer did on the day it was
    captured; the six defects of rounds 2 and 3 would all have passed that.

S2ED reserves two mapper segments, `DIRSEG` and `FTRSEG` -- and on S2 `FTRSEG`
is also the video shadow, so on the default machine there is nothing spare
(`SEGAVL = 0`), which is the point of using it.
"""

import pattern
from cases import Case, crlf
from harness import MACH_MSX1
from keys import Timeline
from result import Check

# The shipped defaults, minus the clock.  A case whose defect is a race must
# turn the clock off or the host RTC moves MAINLOOP's phase between runs and it
# passes and fails at random (learned on D8).
S2_CFG = """; generated by the S2ED test harness
PROFILE=STD
WRAP=TXT
MARKUP=OFF
CLOCK=0
TABWIDTH=4
EOL=AUTO
AUTOALIGN=OFF
"""


class S2Case(Case):
    machine = MACH_MSX1
    cfg = S2_CFG


def one(runs):
    return runs[None]


def font(ctx):
    return pattern.load_font(ctx)


# --- S2-1  THE SCREEN IS WHAT THE DOCUMENT SAYS -----------------------


class S21Render(S2Case):
    name = 'S2-1-render'
    desc = 'every painted row matches a pattern table computed from the font'
    origin = ('round 1: RENDEROW called COMROW with B destroyed by LINEREAD s '
               'LDIR, so every text row composed on top of row 0 and what '
               'reached the screen was whatever FTRSEG held there')
    LINES = ['%02d %s' % (i, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'[:1 + i % 26])
             for i in range(40)]

    def fixture(self, ctx, variant=None):
        return crlf(self.LINES)

    def timeline(self, ctx, variant=None):
        t = Timeline()
        t.snap('boot', vram='patcol')
        return t

    def verify(self, ctx, runs):
        run = one(runs)
        dump = run.blob('boot', 'patcol')
        checks = []
        if dump is None:
            return [Check('S2-1/dump', False, 'no VRAM dump')]
        pat, col = dump[:0x2000], dump[0x2000:]
        bad = pattern.mismatched_rows(
            pat, font(ctx), self.LINES, run.var('boot', 'TOPLINE'),
            cursor=(pattern.TXRFIRST + run.var('boot', 'CURY'),
                    run.var('boot', 'CURX')))
        checks.append(Check('S2-1/rows', not bad,
                            '%d text rows match the computed table'
                            % pattern.ROWSVIS if not bad else
                            'rows differ: %s' % bad[:6]))
        checks.append(Check('S2-1/totlines',
                            run.var('boot', 'TOTLINES') == len(self.LINES),
                            'TOTLINES = %s (expected %d)'
                            % (run.var('boot', 'TOTLINES'), len(self.LINES))))
        # FTRSEG is the video shadow as well as the feature container, so a
        # boot that did not claim both segments is a different bug wearing
        # this case's clothes.
        checks.append(Check('S2-1/segments', run.var('boot', 'SEGCNT') == 2,
                            'SEGCNT = %s (DIRSEG + FTRSEG)'
                            % run.var('boot', 'SEGCNT')))
        uniform, colours = pattern.uniform_colour_cells(col, pattern.TXRFIRST)
        checks.append(Check('S2-1/colour-expand', uniform == pattern.CELLS,
                            '%d/%d cells uniform across their 8 scanlines'
                            % (uniform, pattern.CELLS)))
        return checks


# --- S2-2  ATTRIBUTES COME UP CLEAN -----------------------------------


class S22Attrs(S2Case):
    name = 'S2-2-attrs'
    desc = 'no line comes up with stray attributes (the yellow bands)'
    origin = ('round 2: CORE/FILEIO.Z8A cleared the attribute half of the '
               'record from offset 81 instead of 1 + TEXTCOLS, so the first '
               '16 attribute bytes of every record were never cleared -- '
               'mostly #FF, which COMCELL reads as ATRBOLD and paints in '
               'COLBOLD, a yellow band down the left of the line')
    LINES = ['%02d %s' % (i, 'X' * 60) for i in range(40)]

    def fixture(self, ctx, variant=None):
        return crlf(self.LINES)

    def timeline(self, ctx, variant=None):
        t = Timeline()
        t.snap('boot', vram='patcol')
        return t

    def verify(self, ctx, runs):
        run = one(runs)
        col = run.blob('boot', 'patcol')
        if col is None:
            return [Check('S2-2/dump', False, 'no VRAM dump')]
        col = col[0x2000:]
        wrong = []
        for row in range(pattern.TXRFIRST, pattern.TXRLAST + 1):
            _, colours = pattern.uniform_colour_cells(col, row)
            other = colours - {pattern.COLTXT}
            if other:
                wrong.append((row, sorted('#%02X' % c for c in other)))
        return [
            Check('S2-2/text-colour', not wrong,
                  'every text cell carries COLTXT (#F1)' if not wrong else
                  'rows with other colours: %s' % wrong[:6]),
            Check('S2-2/no-bold',
                  not any(pattern.COLBOLD in dict(wrong).get(r, [])
                          for r in range(pattern.TXRFIRST,
                                         pattern.TXRLAST + 1)),
                  'no COLBOLD anywhere in the text band'),
        ]


# --- S2-3  THE CURSOR IS ONE COLUMN WIDE ------------------------------


class S23Cursor(S2Case):
    name = 'S2-3-cursor'
    desc = 'the cursor inverts exactly one text column'
    origin = ('round 2: the cursor swapped the FG/BG nibbles of the cell s '
               'colour byte.  Screen 2 colour addresses 8x1 SLICES and a cell '
               'holds two 4 px characters, so the finest thing a colour swap '
               'can invert is two columns.  PATINV inverts the pattern bits '
               'of the four pixel columns the text column owns instead.')
    LINES = ['CURSOR ON THIS LINE', 'SECOND LINE']

    def fixture(self, ctx, variant=None):
        return crlf(self.LINES)

    # The cursor blinks: MAINLOOP toggles BLNKPH every 20 JIFFY ticks (0.4 s
    # at 50 Hz), so a single sample can catch it drawn or erased and proves
    # nothing on its own.  Two rules make this deterministic:
    #
    #   * every sample is checked AGAINST ITS OWN BLNKPH -- erased must equal
    #     the plain render, drawn must equal it with one column inverted;
    #   * the sample intervals are deliberately uneven.  The first version
    #     spaced them evenly and every one landed in the same phase: a snap
    #     costs 0.6 s and the wait was 0.22 s, so BLNKCNT advanced 40-41 ticks
    #     between samples -- exactly two toggles.  Measured, all five read
    #     BLNKPH = 0 and the case failed against a cursor that was working.
    #
    # The last sample does not rely on the free-running blink at all: a
    # keystroke ends in .DRAWCUR, which draws the cursor and sets BLNKPH = 1,
    # so LEFT + RIGHT returns to the same column with the cursor guaranteed up.
    SAMPLES = 4

    def timeline(self, ctx, variant=None):
        t = Timeline()
        t.press('RIGHT', repeat=5)
        for i in range(self.SAMPLES):
            t.snap('s%d' % i, vram='pat')
            t.wait(0.1 * i)
        t.press('LEFT')
        # A short tail on purpose: .DRAWCUR runs just after key-down, and the
        # blink toggles 20 JIFFY ticks later.  The default 0.35 s tail puts
        # the sample 30 ticks after the keystroke -- past the toggle, cursor
        # already erased.  0.05 s puts it at ~15.
        t.press('RIGHT', tail=0.05)
        t.snap('drawn', vram='pat')
        return t

    def verify(self, ctx, runs):
        run = one(runs)
        curx = run.var('s0', 'CURX')
        row = pattern.TXRFIRST + (run.var('s0', 'CURY') or 0)
        plain = pattern.compose_row(font(ctx), self.LINES[0])
        inverted = pattern.invert_column(plain, curx)

        wrong, phases = [], []
        for label in ['s%d' % i for i in range(self.SAMPLES)] + ['drawn']:
            pat = run.blob(label, 'pat')
            if pat is None:
                wrong.append('%s: no dump' % label)
                continue
            got = pattern.row_of(pat, row)
            ph = run.var(label, 'BLNKPH')
            phases.append(ph)
            want = inverted if ph == 1 else plain
            cols = pattern.differing_columns(got, want)
            if cols:
                wrong.append('%s (BLNKPH=%s): columns %s' % (label, ph, cols))

        drawn = run.var('drawn', 'BLNKPH')
        got = run.blob('drawn', 'pat')
        one_col = (pattern.differing_columns(
            pattern.row_of(got, row), plain) == [curx]) if got else False
        return [
            Check('S2-3/curx', curx == 5, 'CURX = %s (expected 5)' % curx),
            Check('S2-3/blink-exact', not wrong,
                  'all %d samples match their own blink phase exactly '
                  '(phases seen: %s)' % (len(phases), phases)
                  if not wrong else '; '.join(wrong[:4])),
            Check('S2-3/drawn-up', drawn == 1,
                  'the cursor is up after a keystroke (BLNKPH = %s)' % drawn),
            Check('S2-3/one-column', one_col,
                  'and it covers exactly one text column'
                  if one_col else 'columns differing: %s'
                  % (pattern.differing_columns(pattern.row_of(got, row), plain)
                     if got else 'no dump')),
        ]


# --- S2-4  SELECTION EXTENDS AND LEAVES NOTHING BEHIND ----------------


class S24Select(S2Case):
    name = 'S2-4-select'
    desc = 'SHIFT+RIGHT inverts every column it covers, and deselect leaves none'
    origin = ('round 2: SELDIFF extends a selection ONE COLUMN at a time, so '
               'with a cell-granularity painter two consecutive deltas landed '
               'on the same cell and their XORs cancelled -- selecting 5..11 '
               'inverted only cell 2, and deselecting left cells 3 and 4 '
               'standing as residue.  The selection engine was never broken, '
               'only the painting.')
    LINES = ['SELECT SOME OF THIS LINE PLEASE', 'SECOND LINE']

    def fixture(self, ctx, variant=None):
        return crlf(self.LINES)

    def timeline(self, ctx, variant=None):
        t = Timeline()
        t.press('RIGHT', repeat=5)
        t.snap('before', vram='pat')
        t.press('RIGHT', mods=['SHIFT'], repeat=6)
        t.snap('selected', vram='pat')
        t.press('LEFT')                     # unshifted: deselect
        t.snap('after', vram='pat')
        return t

    def verify(self, ctx, runs):
        run = one(runs)
        checks = []
        plain = pattern.compose_row(font(ctx), self.LINES[0])
        row = pattern.TXRFIRST + (run.var('selected', 'CURY') or 0)
        sel = run.blob('selected', 'pat')
        after = run.blob('after', 'pat')
        if sel is None or after is None:
            return [Check('S2-4/dump', False, 'missing VRAM dump')]
        checks.append(Check('S2-4/selact',
                            run.var('selected', 'SELACT') == 1,
                            'SELACT = %s' % run.var('selected', 'SELACT')))
        inv = pattern.inverted_columns(pattern.row_of(sel, row), plain)
        # The cursor is itself an inversion and sits at one end of the range,
        # so the inverted set is the selected columns, cursor included.
        want = list(range(5, 12))
        checks.append(Check('S2-4/range', inv == want,
                            'columns %d..%d inverted' % (want[0], want[-1])
                            if inv == want else 'inverted: %s' % inv))
        # After deselecting, only the cursor cell may differ from the document.
        curx = run.var('after', 'CURX')
        diff = pattern.differing_columns(pattern.row_of(after, row), plain)
        residue = [c for c in diff if c != curx]
        checks.append(Check('S2-4/no-residue', not residue,
                            'zero columns left inverted after deselect'
                            if not residue else 'residue at %s' % residue))
        return checks


# --- S2-5  THE CURSOR STAYS INSIDE THE TEXT BAND ----------------------


class S25Band(S2Case):
    name = 'S2-5-band'
    desc = 'the viewport scrolls at the bottom of the TEXT BAND, not the screen'
    origin = ('round 2: sixteen sites in CORE bounded the cursor with '
               'SCRROWS (24, the physical screen) where they meant ROWSVIS '
               '(22, the text band).  The cursor walked two rows below the '
               'painted band before the viewport scrolled -- from the '
               'keyboard, "the scroll does not work" -- and DRWCUR then '
               'addressed CTBASE + 24 * 256 = #3800, putting 8 bytes into '
               'the sprite generator table.')
    LINES = ['LINE %03d' % i for i in range(60)]

    def fixture(self, ctx, variant=None):
        return crlf(self.LINES)

    def timeline(self, ctx, variant=None):
        t = Timeline()
        t.press('DOWN', repeat=33)
        t.snap('descended', vram='pat')
        return t

    def verify(self, ctx, runs):
        run = one(runs)
        cury = run.var('descended', 'CURY')
        topline = run.var('descended', 'TOPLINE')
        docline = run.var('descended', 'DOCLINE')
        pat = run.blob('descended', 'pat')
        checks = [
            Check('S2-5/cury', cury == pattern.ROWSVIS - 1,
                  'CURY = %s (expected %d, the last visible row)'
                  % (cury, pattern.ROWSVIS - 1)),
            Check('S2-5/viewport', topline == docline - cury,
                  'TOPLINE %s = DOCLINE %s - CURY %s'
                  % (topline, docline, cury)),
        ]
        if pat is not None:
            bad = pattern.mismatched_rows(
                pat, font(ctx), self.LINES, topline,
                cursor=(pattern.TXRFIRST + cury,
                        run.var('descended', 'CURX')))
            checks.append(Check('S2-5/scrolled-rows', not bad,
                                'the scrolled screen matches the document'
                                if not bad else 'rows differ: %s' % bad[:6]))
        return checks


# --- S2-6  BACKSPACE, THEN KEEP TYPING --------------------------------


class S26DelType(S2Case):
    name = 'S2-6-deltype'
    desc = 'typing still works after BACKSPACE and after DEL'
    origin = ('round 3: EDDELBK and EDDELCHR ran their shift loop to a hard '
               '79 and blanked WORKBUF + 80.  On a 1+64+64 record that drags '
               'the attribute byte of column 0 into the LAST TEXT COLUMN, '
               'after which EDINSCHR sees a full record and refuses every '
               'keystroke on that line -- silently, in WRAP_DEV.  LINEWRT '
               'persists it, so the line stays poisoned.')
    LINES = ['HELLO MSX WORLD', 'SECOND LINE']
    # Both delete keys and both wrap modes.  The mode matters: in WRAP_DEV the
    # refused insert is a mute RET NZ -- the user's "it just stops typing" --
    # while in WRAP_TXT it goes to EDPSHWR and shows up as a spurious wrap
    # instead, which is why TOTLINES is asserted as well as the text.
    variants = ('bs-dev', 'del-dev', 'bs-txt', 'del-txt')

    def fixture(self, ctx, variant=None):
        return crlf(self.LINES)

    def config(self, ctx, variant=None):
        mode = 'DEV' if variant.endswith('-dev') else 'TXT'
        return self.cfg.replace('WRAP=TXT', 'WRAP=' + mode)

    def timeline(self, ctx, variant=None):
        t = Timeline()
        for k in 'LABEL':
            t.press(k)
        t.snap('typed')
        t.press('BS' if variant.startswith('bs') else 'DEL', repeat=3)
        t.snap('deleted')
        t.press('X')
        t.press('S', mods=['CTRL'])
        t.wait(3.0)
        t.snap('saved', vram='pat')
        return t

    def verify(self, ctx, runs):
        checks = []
        for variant, run in sorted(runs.items()):
            # keymatrixdown without SHIFT delivers lowercase.
            head = self.LINES[0]
            if variant.startswith('bs'):
                want_first = 'la' + 'x' + head       # 5 typed, 3 removed
            else:
                want_first = 'label' + 'x' + head[3:]  # DEL eats 3 ahead
            typed = run.var('typed', 'CURX')
            checks.append(Check('S2-6/%s/typed' % variant, typed == 5,
                                'CURX = %s after typing LABEL' % typed))
            got = run.session.extract(run.dsk, 'DOC.TXT')
            first = (got or b'').split(b'\r\n')[0].decode('ascii', 'replace')
            tot = run.var('saved', 'TOTLINES')
            checks.append(Check('S2-6/%s/totlines' % variant,
                                tot == len(self.LINES),
                                'TOTLINES = %s (expected %d: nothing wrapped)'
                                % (tot, len(self.LINES))))
            checks.append(Check('S2-6/%s/line' % variant, first == want_first,
                                'line reads %r' % first if first == want_first
                                else 'line reads %r, expected %r'
                                     % (first, want_first)))
            pat = run.blob('saved', 'pat')
            if pat is not None:
                lines = [want_first] + self.LINES[1:]
                bad = pattern.mismatched_rows(
                    pat, font(ctx), lines, run.var('saved', 'TOPLINE'),
                    cursor=(pattern.TXRFIRST + run.var('saved', 'CURY'),
                            run.var('saved', 'CURX')))
                checks.append(Check('S2-6/%s/screen' % variant, not bad,
                                    'screen agrees with the document'
                                    if not bad else 'rows differ: %s' % bad[:4]))
        return checks


# --- S2-7  ENTER ON THE LAST VISIBLE ROW ------------------------------


class S27EnterBot(S2Case):
    name = 'S2-7-enterbot'
    desc = 'splitting on the last visible row repaints the head, not the status bar'
    origin = ('round 3: EDNWLIN repainted the shortened head with a literal '
               'LD B, 23 -- the row below the last visible one on S2, which '
               'is the STATUS BAR.  The head at row 21 was left stale and the '
               'status bar was painted over with document text.')
    LINES = ['LINE %03d ABCDEFGHIJ' % i for i in range(40)]

    def fixture(self, ctx, variant=None):
        return crlf(self.LINES)

    def timeline(self, ctx, variant=None):
        t = Timeline()
        t.press('DOWN', repeat=25)          # well past the bottom of the band
        t.press('RIGHT', repeat=4)          # split mid-line
        t.snap('atbottom', vram='patcol')
        t.press('RETURN')
        t.snap('split', vram='patcol')
        t.press('S', mods=['CTRL'])
        t.wait(3.0)
        t.snap('saved')
        return t

    def verify(self, ctx, runs):
        run = one(runs)
        before = run.blob('atbottom', 'patcol')
        after = run.blob('split', 'patcol')
        if before is None or after is None:
            return [Check('S2-7/dump', False, 'missing VRAM dump')]
        checks = [
            Check('S2-7/at-band-bottom',
                  run.var('atbottom', 'CURY') == pattern.ROWSVIS - 1,
                  'CURY = %s before the split'
                  % run.var('atbottom', 'CURY')),
            Check('S2-7/totlines',
                  run.var('split', 'TOTLINES') == len(self.LINES) + 1,
                  'TOTLINES = %s (expected %d)'
                  % (run.var('split', 'TOTLINES'), len(self.LINES) + 1)),
        ]
        # The status bar is chrome.  It may legitimately change (the modified
        # marker), but it must still be CHROME: with LD B, 23 the split
        # painted a document line there, in COLTXT.
        _, colours = pattern.uniform_colour_cells(after[0x2000:],
                                                  pattern.STBROW)
        checks.append(Check(
            'S2-7/status-is-chrome', colours == {pattern.COLUI},
            'the status bar is still painted in COLUI (#1F)'
            if colours == {pattern.COLUI} else
            'status bar colours: %s' % sorted('#%02X' % c for c in colours)))
        head_row = pattern.row_of(after[:0x2000], pattern.STBROW)
        band_row = pattern.row_of(after[:0x2000], pattern.TXRLAST)
        checks.append(Check(
            'S2-7/status-not-text', head_row != band_row,
            'the status bar does not carry a copy of a document row'))
        # And the whole band must agree with the document that was saved.
        got = run.session.extract(run.dsk, 'DOC.TXT')
        lines = (got or b'').decode('ascii', 'replace').split('\r\n')
        while lines and lines[-1] == '':
            lines.pop()
        bad = pattern.mismatched_rows(
            after[:0x2000], font(ctx), lines, run.var('split', 'TOPLINE'),
            cursor=(pattern.TXRFIRST + run.var('split', 'CURY'),
                    run.var('split', 'CURX')))
        checks.append(Check('S2-7/head-repainted', not bad,
                            'every band row agrees with the saved document'
                            if not bad else 'rows differ: %s' % bad[:6]))
        return checks


# --- S2-8  DIFFERENTIAL PAINTERS AGREE WITH A FULL REDRAW -------------


class S28RenderPure(S2Case):
    name = 'S2-8-renderpure'
    desc = 'after a burst of edits the screen equals a full REDRAW of the document'
    origin = ('the G7 idea, which is the one general case in the S6 gate: a '
               'REDRAW repaints from the document alone, so forcing one and '
               'diffing tests every differential painter at once.  Here it is '
               'checked BOTH ways -- against the REDRAW and against the '
               'computed table -- so a renderer that is consistently wrong '
               'still fails.')
    LINES = ['ROW %03d %s' % (i, 'abcdefghijklmnop') for i in range(30)]

    def fixture(self, ctx, variant=None):
        return crlf(self.LINES)

    # The edits end with a SPLIT, deliberately.  The first version ended with
    # BACKSPACE at column 0, which in WRAP_TXT cascades REFLOW and finishes
    # with a full REDRAW -- repainting the whole screen microseconds before
    # the sample and blinding the case: a mutation that dropped SHIFTDNN's
    # VRAM push went clean through it.  A mid-document Enter uses SHIFTDN and
    # two RENDEROW calls and repaints nothing else, so whatever those leave
    # behind is still on screen when 'edited' is taken.
    def timeline(self, ctx, variant=None):
        t = Timeline()
        t.press('DOWN', repeat=3)
        t.press('RIGHT', repeat=5)
        for k in 'ZZ':
            t.press(k)                  # in-line insert  -> RENDIFF
        t.press('BS')                   # in-line delete  -> RENDIFF
        t.press('DEL', repeat=2)
        t.press('DOWN', repeat=2)
        t.press('RIGHT', repeat=4)
        t.press('RETURN')               # mid-document split -> SHIFTDN
        t.press('S', mods=['CTRL'])
        t.wait(3.0)
        t.snap('edited', vram='patcol')
        # GRAPH+DOWN / GRAPH+UP page down and back: the viewport returns to
        # where it was and the screen is repainted wholesale on the way.
        t.press('DOWN', mods=['GRAPH'])
        t.press('UP', mods=['GRAPH'])
        t.snap('redrawn', vram='patcol')
        return t

    def verify(self, ctx, runs):
        run = one(runs)
        a, b = run.blob('edited', 'patcol'), run.blob('redrawn', 'patcol')
        if a is None or b is None:
            return [Check('S2-8/dump', False, 'missing VRAM dump')]
        same_state = all(run.var('edited', k) == run.var('redrawn', k)
                         for k in ('TOPLINE', 'DOCLINE', 'CURX', 'CURY',
                                   'TOTLINES'))
        checks = [Check('S2-8/same-state', same_state,
                        'the page round trip returned to the same position')]
        if not same_state:
            checks.append(Check('S2-8/render-pure', False,
                                'state mismatch before diff'))
            return checks
        cury = run.var('edited', 'CURY')
        rows = [r for r in range(pattern.ROWS)
                if pattern.row_of(a[:0x2000], r) != pattern.row_of(b[:0x2000], r)
                and r != pattern.TXRFIRST + cury]
        checks.append(Check('S2-8/render-pure', not rows,
                            'screen identical to a full REDRAW'
                            if not rows else 'rows differ: %s' % rows))
        got = run.session.extract(run.dsk, 'DOC.TXT')
        lines = (got or b'').decode('ascii', 'replace').split('\r\n')
        while lines and lines[-1] == '':
            lines.pop()
        bad = pattern.mismatched_rows(
            b[:0x2000], font(ctx), lines, run.var('redrawn', 'TOPLINE'),
            cursor=(pattern.TXRFIRST + cury, run.var('redrawn', 'CURX')))
        checks.append(Check('S2-8/matches-document', not bad,
                            'and it agrees with the document on disk'
                            if not bad else 'rows differ: %s' % bad[:6]))
        return checks


# --- S2-9  THE RIGHT MARGIN -------------------------------------------


class S29Margin(S2Case):
    name = 'S2-9-margin'
    desc = 'an edit at the right margin of a FULL line is an append'
    origin = ('the same CORE defect D11-margin covers, seen on the 64-column '
               'record and with the screen checked as well as the document: '
               'the cursor cannot park past the last column of a full line, '
               'so an edit taken at the clamped column landed one place too '
               'early -- typing X on a line ending in HELLO wrapped it as '
               '"HELLxO", and a space at the margin carried the "O" down.')
    TAIL = 'HELLO'
    LINE = 'A' * (pattern.COLS - len(TAIL) - 1) + ' ' + TAIL
    LINES = [LINE, 'SECOND LINE']
    variants = ('push', 'space')

    def fixture(self, ctx, variant=None):
        return crlf(self.LINES)

    def timeline(self, ctx, variant=None):
        t = Timeline()
        t.press('RIGHT', mods=['CTRL'])         # ACEOL: clamps to COLS - 1
        t.snap('ateol')
        t.press('X' if variant == 'push' else 'SPACE')
        t.press('S', mods=['CTRL'])
        t.wait(3.0)
        t.snap('done', vram='pat')
        return t

    def verify(self, ctx, runs):
        checks = []
        for variant, run in sorted(runs.items()):
            pre = 'S2-9/%s' % variant
            checks.append(Check('%s/clamped' % pre,
                                run.var('ateol', 'CURX') == pattern.COLS - 1,
                                'ACEOL leaves CURX = %s on a full line'
                                % run.var('ateol', 'CURX')))
            if variant == 'push':
                want = [self.LINE[:pattern.COLS - len(self.TAIL)],
                        self.TAIL + 'x', 'SECOND LINE']
                curx = len(self.TAIL) + 1
            else:
                want = [self.LINE, '', 'SECOND LINE']
                curx = 0
            got = run.session.extract(run.dsk, 'DOC.TXT')
            lines = (got or b'').decode('ascii', 'replace').split('\r\n')
            while lines and lines[-1] == '':
                lines.pop()
            checks.append(Check('%s/content' % pre, lines == want,
                                'document breaks correctly' if lines == want
                                else 'got %r' % (lines[:2],)))
            checks.append(Check('%s/curx' % pre,
                                run.var('done', 'CURX') == curx,
                                'CURX = %s (expected %d)'
                                % (run.var('done', 'CURX'), curx)))
            pat = run.blob('done', 'pat')
            if pat is not None:
                bad = pattern.mismatched_rows(
                    pat, font(ctx), want, run.var('done', 'TOPLINE'),
                    cursor=(pattern.TXRFIRST + run.var('done', 'CURY'), curx))
                checks.append(Check('%s/screen' % pre, not bad,
                                    'the screen shows the broken text'
                                    if not bad else 'rows differ: %s' % bad[:4]))
        return checks


CASES = [S21Render(), S22Attrs(), S23Cursor(), S24Select(), S25Band(),
         S26DelType(), S27EnterBot(), S28RenderPure(), S29Margin()]


def run(ctx, cases=None):
    """Execute the S2 gate against an S2ED context.  Same shape as gate.run."""
    checks = []
    for case in (cases if cases is not None else CASES):
        try:
            runs = case.execute(ctx)
        except Exception as exc:                          # noqa: BLE001
            checks.append(Check(case.name, False, 'harness error: %s' % exc))
            continue
        broken = [v for v, r in runs.items()
                  if r.timed_out or 'DONE' not in r.lines]
        if broken:
            checks.append(Check(case.name, False,
                                'session did not finish: %s'
                                % ', '.join(str(v) for v in broken)))
            continue
        try:
            checks += case.verify(ctx, runs)
        except Exception as exc:                          # noqa: BLE001
            checks.append(Check(case.name, False,
                                'verify error: %s: %s'
                                % (type(exc).__name__, exc)))
    return checks
