"""Suite S62 -- the S62ED gate: MSX2 SCREEN 6, 62 columns of 8x8 cells.

S62ED shares CORE with S6ED and S2ED and has its own driver (S62/).  It was
cloned from S6ED's 6x8 code, and every defect found in it so far was a 6 px
measurement left behind: text insets, window and button sizes, a status bar
field, menu items that fit at 6 px and lost their last glyph at 8.  So the
verdicts here are computed, never captured: screen62.py derives the expected
image of every cell from S62ED.FNT and the document, as pattern.py does for
S2ED.  The machine is the stock 128 kB NMS 8250, the minimum target.
"""

import os

import screen62
from cases import Case, ShippedDiskCase, crlf, numbered
from gate import asciiz
from harness import MACH_128K, MACH_2MB
from keys import Timeline
from result import Check


S62_CFG = """; generated by the S62ED test harness
PROFILE=STD
WRAP=DEV
MARKUP=OFF
CLOCK=0
TABWIDTH=4
EOL=AUTO
AUTOALIGN=OFF
THEME=DARK
"""


class S62Case(Case):
    machine = MACH_128K
    cfg = S62_CFG


def one(runs):
    return runs[None]


def font(ctx):
    return screen62.load_font(ctx)


def screen_checks(tag, ctx, run, label, lines, cursor=True):
    """The text area, its margins and the status bar against the model."""
    dump = run.blob(label, 'screen')
    fnt = font(ctx)
    if dump is None or fnt is None:
        return [Check('%s/dump' % tag, False,
                      'no screen dump' if dump is None else 'no S62ED.FNT')]
    top = run.var(label, 'TOPLINE') or 0
    left = run.var(label, 'LEFTCOL') or 0
    cur = None
    if cursor:
        cur = (run.var(label, 'CURY'), run.var(label, 'CURX') - left)
    bad = screen62.text_mismatches(dump, fnt, lines, top, left, cur)
    margin = screen62.margin_dirty(dump)
    stat = run.snaps.get(label, {}).get('STATBUF') or []
    sbad = screen62.status_mismatches(dump, fnt, stat)
    return [
        Check('%s/text' % tag, not bad,
              '%d x %d cells match the font' % (screen62.ROWS, screen62.COLS)
              if not bad else '%d cells differ, first %s' % (len(bad), bad[:6])),
        Check('%s/margins' % tag, not margin,
              '8 px margins clean' if not margin else
              'ink in the margins on scanlines %s' % margin[:6]),
        Check('%s/status' % tag, not sbad,
              'status bar cells match STATBUF' if not sbad else
              'status bar columns differ: %s' % sbad[:8]),
    ]


# --- S62-1  THE BOOT SCREEN IS THE DOCUMENT -----------------------------


class S621Render(S62Case):
    name = 'S62-1-render'
    desc = ('the boot screen matches an image computed from S62ED.FNT: text, '
            'margins, status bar and menu bar')
    origin = ('S62ED was cloned from 6x8 code; 2026-10-06 audit found the '
              'text insets and widths still at 6 px')
    FULL = ''.join(chr(0x41 + (i % 26)) for i in range(62))
    LINES = (['L%02d %s' % (i, 'abcdefghijklmnopqrstuvwxyz'[:1 + i % 26])
              for i in range(30)] +
             [FULL, '', '\xa0\x82\xa1\xa2\xa3 \xa4\xa5 \x81 \xad\xa8',
              '    indented', '~!@#$%^&*()_+{}|:"<>?'])

    def fixture(self, ctx, variant=None):
        return ('\r\n'.join(self.LINES) + '\r\n').encode('latin-1')

    def timeline(self, ctx, variant=None):
        t = Timeline()
        t.snap('boot', vram='screen')
        return t

    def verify(self, ctx, runs):
        run = one(runs)
        checks = screen_checks('S62-1', ctx, run, 'boot', self.LINES)
        dump = run.blob('boot', 'screen')
        fnt = font(ctx)
        menu = (screen62.cell_text(dump, fnt, 16, 0, 25, screen62.COL_FG,
                                   screen62.COL_UI)
                if dump is not None and fnt is not None else None)
        want = 'S61ED | File  Edit  Help'
        checks.append(Check('S62-1/menubar', menu == want,
                            'row 0 reads %r' % menu))
        checks.append(Check('S62-1/totlines',
                            run.var('boot', 'TOTLINES') == len(self.LINES),
                            'TOTLINES = %s (expected %d)'
                            % (run.var('boot', 'TOTLINES'), len(self.LINES))))
        return checks


# --- S62-2  EDITING PATHS REPAINT WHAT THE DOCUMENT HOLDS ----------------


class S622Edit(S62Case):
    name = 'S62-2-edit'
    desc = ('type, split, join and delete: the screen after each differential '
            'repaint matches the computed image, and the file saved matches')
    origin = ('RENDIFF / SHIFTDNN / EDDELCHR repaint only what changed; in '
              'S62 every cell they address is 8 px, not 6')
    LINES = numbered(12)

    def fixture(self, ctx, variant=None):
        return crlf(self.LINES)

    def expected(self):
        out = list(self.LINES)
        out[0] = 'XY' + out[0]
        out[1] = out[1][:2] + out[1][3:]
        return out

    def timeline(self, ctx, variant=None):
        t = Timeline()
        t.snap('boot')
        t.text('XY')
        t.wait(0.5)
        t.press('RETURN')
        t.wait(0.5)
        t.snap('split', vram='screen')
        t.press('BS')
        t.press('DOWN')
        t.press('DEL')
        t.wait(1.0)
        t.snap('edited', vram='screen')
        t.press('S', mods=['CTRL'])
        t.wait(2.0)
        t.snap('saved')
        return t

    def verify(self, ctx, runs):
        run = one(runs)
        split = ['XY', self.LINES[0]] + self.LINES[1:]
        checks = screen_checks('S62-2/split', ctx, run, 'split', split)
        checks += screen_checks('S62-2/edited', ctx, run, 'edited',
                                self.expected())
        got = run.session.extract(run.dsk, 'DOC.TXT')
        want = crlf(self.expected())
        checks.append(Check('S62-2/saved', got == want,
                            'file on disk matches byte for byte'
                            if got == want else 'got %r' % (got or b'')[:80]))
        return checks


# --- S62-3  VERTICAL SCROLL ---------------------------------------------


class S623Scroll(S62Case):
    name = 'S62-3-scroll'
    desc = ('cursor runs past the bottom, then to the top and the end of the '
            'document: every viewport matches the computed image')
    origin = 'the YMMM scroll and the exposed-row repaint, at 8 px rows'
    # Every column must differ from the line above, the first one included:
    # with numbered() every line starts with 'L', and a scroll that leaves
    # column 0 behind would still show the right glyph.
    LINES = ['%s%02d %s' % (chr(0x41 + i % 26), i, chr(0x61 + i % 26) * (i % 50))
             for i in range(60)]

    def fixture(self, ctx, variant=None):
        return crlf(self.LINES)

    def timeline(self, ctx, variant=None):
        t = Timeline()
        t.snap('boot')
        t.press('DOWN', repeat=30)
        t.wait(1.0)
        t.snap('down', vram='screen')
        t.press('DOWN', mods=['CTRL'])
        t.wait(1.0)
        t.snap('bottom', vram='screen')
        t.press('UP', repeat=3)
        t.wait(1.0)
        t.snap('up', vram='screen')
        return t

    def verify(self, ctx, runs):
        run = one(runs)
        checks = []
        for label in ('down', 'bottom', 'up'):
            checks += screen_checks('S62-3/%s' % label, ctx, run, label,
                                    self.LINES)
        checks.append(Check('S62-3/scrolled',
                            (run.var('down', 'TOPLINE') or 0) > 0 and
                            run.var('bottom', 'DOCLINE') == len(self.LINES) - 1,
                            'TOPLINE %s after 30 DOWN, DOCLINE %s at the end'
                            % (run.var('down', 'TOPLINE'),
                               run.var('bottom', 'DOCLINE'))))
        return checks


# --- S62-4  HORIZONTAL SCROLL AND THE COLUMN FIELD ----------------------


class S624HScroll(S62Case):
    name = 'S62-4-hscroll'
    desc = ('a 120-column line: the viewport scrolls left past column 62 and '
            'the status bar reads Col 121 with three digits')
    origin = ('the status bar took S6ED\'s "  Col " with S2ED\'s two digits: '
              'Col01, and wrong past column 99')
    LONG = ''.join('%d' % (i % 10) for i in range(120))
    LINES = [LONG, 'SECOND', 'THIRD']

    def fixture(self, ctx, variant=None):
        return crlf(self.LINES)

    def timeline(self, ctx, variant=None):
        t = Timeline()
        t.snap('boot')
        t.press('RIGHT', mods=['CTRL'])
        t.wait(1.0)
        t.snap('end', vram='screen')
        t.press('LEFT', mods=['CTRL'])
        t.wait(1.0)
        t.snap('home', vram='screen')
        return t

    def verify(self, ctx, runs):
        run = one(runs)
        checks = screen_checks('S62-4/end', ctx, run, 'end', self.LINES)
        checks += screen_checks('S62-4/home', ctx, run, 'home', self.LINES)
        stat = bytes(run.snaps.get('end', {}).get('STATBUF') or b'')
        stat = stat.split(b'\0')[0].decode('latin-1')
        checks.append(Check('S62-4/scrolled',
                            (run.var('end', 'LEFTCOL') or 0) > 0 and
                            run.var('home', 'LEFTCOL') == 0,
                            'LEFTCOL %s at the end, %s back home'
                            % (run.var('end', 'LEFTCOL'),
                               run.var('home', 'LEFTCOL'))))
        checks.append(Check('S62-4/col', stat.rstrip().endswith('Col 121'),
                            'status bar right block: %r' % stat[-24:]))
        return checks


# --- S62-5  MENU AND WINDOW TEXT FITS ITS 8 PX CELLS --------------------


class S625Windows(S62Case):
    name = 'S62-5-windows'
    desc = ('File menu items and the About title read back whole, at the '
            'WINX + 8 inset WINPCO uses for body text')
    origin = ('2026-10-06: title and menu text drawn at WINX + 6, and 22-char '
              'items lost their last glyph to WINCLIPX ("Ctrl+")')
    variants = ('file', 'about')
    ITEMS = {1: 'Open...       Ctrl+O', 2: 'Save          Ctrl+S',
             5: 'Quit          Ctrl+Q'}
    YTBL = (0x03, 0x0B, 0x13, 0x1B, 0x25, 0x29)

    def fixture(self, ctx, variant=None):
        return crlf(numbered(5))

    def timeline(self, ctx, variant=None):
        t = Timeline()
        t.snap('boot')
        if variant == 'file':
            t.press('F1')
        else:
            t.press('F5')
            t.wait(0.5)
            t.press('A')
        t.wait(1.0)
        t.snap('win', vram='screen', at='WINPOLL')
        t.wait(0.5)
        t.press('ESC')
        t.wait(0.5)
        return t

    def verify(self, ctx, runs):
        checks = []
        fnt = font(ctx)
        for variant, run in runs.items():
            tag = 'S62-5/%s' % variant
            dump = run.blob('win', 'screen')
            if dump is None or fnt is None:
                checks.append(Check(tag, False, 'no screen dump'))
                continue
            wx, wy = run.var('win', 'WINX'), run.var('win', 'WINY')
            if variant == 'file':
                bad = []
                for idx, want in sorted(self.ITEMS.items()):
                    got = screen62.cell_text(dump, fnt, wx + 8,
                                             wy + self.YTBL[idx], len(want))
                    if got != want:
                        bad.append((want, got))
                checks.append(Check('%s/items' % tag, not bad,
                                    'items read back whole at WINX + 8'
                                    if not bad else 'item text: %s' % bad))
            else:
                want = 'About S61ED'
                bold = screen62.load_font(ctx, screen62.BOLD)  # WINSTR3, variant 1
                got = screen62.cell_text(dump, bold, wx + 8, wy + 2, len(want),
                                         screen62.COL_HI, screen62.COL_UI)
                checks.append(Check('%s/title' % tag, got == want,
                                    'title bar reads %r' % got))
        return checks


# --- S62-6  FILE BROWSER GEOMETRY ---------------------------------------


class S626Browse(S62Case):
    name = 'S62-6-browse'
    desc = ('the browser is 456 x 176 at (28, 18) and its information line '
            'reads back exactly as BRWINF, last column included')
    origin = ('2026-10-06: window sized for 14 rows and 6 px cells, a grid '
              '8 px narrower than the line, and the count\'s last digit clipped')

    def fixture(self, ctx, variant=None):
        return crlf(numbered(5))

    def timeline(self, ctx, variant=None):
        t = Timeline()
        t.snap('boot')
        t.press('O', mods=['CTRL'])
        t.wait(2.0)
        t.snap('brw', vram='screen', at='WINPOLL')
        t.wait(0.5)
        t.press('ESC')
        t.wait(1.0)
        return t

    def verify(self, ctx, runs):
        run = one(runs)
        geo = tuple(run.var('brw', v) for v in ('WINX', 'WINY', 'WINW', 'WINH'))
        checks = [Check('S62-6/geometry', geo == (28, 18, 456, 176),
                        'WINX, WINY, WINW, WINH = %s' % (geo,))]
        dump = run.blob('brw', 'screen')
        fnt = font(ctx)
        raw = run.snaps.get('brw', {}).get('BRWINF')
        if dump is None or fnt is None or raw is None:
            return checks + [Check('S62-6/info', False, 'no dump or BRWINF')]
        want = bytes(raw).split(b'\0')[0].decode('latin-1')
        y = run.var('brw', 'WINY') + 16 + 13 * 8      # BRWLSTY + BRWINFR * 8
        got = screen62.cell_text(dump, fnt, run.var('brw', 'WINX') + 8, y,
                                 len(want), screen62.COL_FG, screen62.COL_UI)
        checks.append(Check('S62-6/info', got == want and want.rstrip(),
                            'information line reads back whole (%d chars)'
                            % len(want) if got == want else
                            'screen %r, BRWINF %r' % (got, want)))
        # The name field's box used to start at x 40 (EDCOL 44, kept from S6)
        # and paint over the ':' of the label, which ends at 47 at 8 px.
        y = run.var('brw', 'WINY') + 16 + 15 * 8      # BRWLSTY + BRWFLDR * 8
        lab = screen62.cell_text(dump, fnt, run.var('brw', 'WINX') + 8, y, 5,
                                 screen62.COL_FG, screen62.COL_BG)
        checks.append(Check('S62-6/name-label', lab == 'Name:',
                            'label reads %r (want \'Name:\')' % lab))
        return checks


# --- S62-7..9  CONTAINER, LOAD PROGRESS, BROWSER NOTICES ----------------


class S627DatForeign(S62Case):
    name = 'S62-7-dat-foreign'
    desc = "S6ED.DAT renamed to S62ED.DAT aborts with the corrupt message"
    origin = 'S62ED shipped S6ED\'s container magic until 2026-10-06'
    absolute = True
    with_dat = False
    autoexec = 'S62ED'
    cfg = None

    def disk_files(self, ctx, variant=None):
        files = S62Case.disk_files(self, ctx, variant)
        with open(os.path.join(ctx.code_dir, 'S6ED.DAT'), 'rb') as fh:
            files['S62ED.DAT'] = fh.read()
        return files

    def timeline(self, ctx, variant=None):
        t = Timeline(start=2.0)
        t.snap('exit', vram='text', at='TERM.TERMDON')
        t.t = 45.0
        return t

    def verify(self, ctx, runs):
        run = one(runs)
        want = b'S62ED.DAT corrupt.'
        text = run.blob('exit', 'text')
        printed = text is not None and want in text
        return [Check('S62-7/corrupt-printed', printed,
                      'text VRAM holds %r' % want if printed else
                      '%r not found in the text-mode name table' % want)]


class S628LoadProgress(S62Case):
    name = 'S62-8-load-progress'
    desc = 'the load bar is full at the end of the read and gone afterwards'
    origin = '2026-10-06: a long load showed nothing and read as a hang'
    absolute = True

    def fixture(self, ctx, variant=None):
        return crlf(numbered(40))

    def timeline(self, ctx, variant=None):
        t = Timeline(start=2.0)
        t.snap('loaded', at='LOADDOC.CLSFIL')
        t.snap('boot', at='MAINLOOP')
        t.t = 45.0
        return t

    def verify(self, ctx, runs):
        run = one(runs)
        raw = run.snaps.get('loaded', {}).get('STATMSG')
        msg = bytes(raw).split(b'\0')[0] if raw is not None else None
        want = b'Loading... ' + b'\xdb' * 10 + b' 100%'
        after = asciiz(run, 'boot', 'STATMSG')
        return [
            Check('S62-8/progress', msg == want,
                  'STATMSG at the end of the read: %r' % msg),
            Check('S62-8/cleared', after == '' and
                  run.var('boot', 'TOTLINES') == 40,
                  'STATMSG %r with %s lines' % (after,
                                                run.var('boot', 'TOTLINES'))),
        ]


class S629BrowseBusy(S62Case):
    name = 'S62-9-browse-busy'
    desc = ('"Reading directory..." on the status bar for the first scan and '
            'on the information line for a rescan')
    origin = '2026-10-06: Ctrl+O left the screen unchanged during the scan'

    def fixture(self, ctx, variant=None):
        return crlf(numbered(5))

    def disk_files(self, ctx, variant=None):
        files = S62Case.disk_files(self, ctx, variant)
        files['SUB\\NOTE.TXT'] = crlf(['NOTE'])
        return files

    def timeline(self, ctx, variant=None):
        t = Timeline()
        t.snap('boot')
        t.snap('scan', at='BRWSCNM.SCAN')
        t.press('O', mods=['CTRL'])
        t.wait(2.0)
        t.snap('busy', at='BRWBUSY.DONE')
        t.press('RETURN')
        t.wait(2.0)
        t.press('ESC')
        t.wait(1.0)
        t.snap('after')
        return t

    def verify(self, ctx, runs):
        run = one(runs)
        scan = asciiz(run, 'scan', 'STATMSG')
        busy = asciiz(run, 'busy', 'BRWINF')
        after = asciiz(run, 'after', 'STATMSG')
        return [
            Check('S62-9/scan', scan == 'Reading directory...',
                  'STATMSG during the first scan: %r' % scan),
            Check('S62-9/busy', busy is not None and
                  busy.startswith('Reading directory...'),
                  'information line during the rescan: %r' % busy),
            Check('S62-9/cleared', after == '',
                  'STATMSG after the browser closed: %r' % after),
        ]


# --- S62-10  THE SHIPPED DISK BOOTS ------------------------------------


class S6210ShippedDisk(ShippedDiskCase):
    name = 'S62-10-shipped-disk'
    desc = 'S62ED.DSK as make dsk-s62 ships it boots into \\DEV\\TEST.TXT'
    origin = ('2026-10-06: AUTOEXEC_S62.BAT had bare LF line endings, which '
              'COMMAND2.COM ignores -- the disk booted to the DOS prompt')
    machine = MACH_128K
    dsk_target = 'dsk-s62'
    dsk_name = 'S62ED.DSK'
    doc_host = 'TEST_S62.TXT'

    def verify(self, ctx, runs):
        return self.shipped_checks(ctx, runs, 'S62-10', Check)


CASES = [S621Render(), S622Edit(), S623Scroll(), S624HScroll(),
         S625Windows(), S626Browse(), S627DatForeign(), S628LoadProgress(),
         S629BrowseBusy(), S6210ShippedDisk()]


def run(ctx, cases=None):
    """Execute the S62 gate.  Same shape as gate.run and gate_s2.run."""
    checks = []
    for case in (cases if cases is not None else CASES):
        try:
            runs = case.execute(ctx)
        except Exception as exc:                          # noqa: BLE001
            checks.append(Check(case.name, False, 'harness error: %s' % exc))
            continue
        broken = [v for v, r in runs.items()
                  if r.timed_out or 'DONE' not in r.lines]
        if broken:
            checks.append(Check(case.name, False,
                                'session did not finish: %s'
                                % ', '.join(str(v) for v in broken)))
            continue
        try:
            checks += case.verify(ctx, runs)
        except Exception as exc:                          # noqa: BLE001
            checks.append(Check(case.name, False,
                                'verify error: %s: %s'
                                % (type(exc).__name__, exc)))
    return checks
